# -*- coding: utf-8 -*-
"""HARD tier: inverted conditionals, subjunctive, clefts, fronted negatives."""

PATTERNS = [
dict(
  hard=True,
  target="Conditional inversion without <i>if</i>",
  why="A conditional can drop <i>if</i> and invert the subject with <i>had</i>, <i>were</i> or <i>should</i> instead: {ans}.",
  extras=["if", "would"],
  items=[
    ("Why didn't you come to the opening?", "Honestly, [had] [I] [known] [about] [it] [earlier], I would have come."),
    ("Could the project have been saved?", "Frankly, [had] [the] [funding] [arrived] [on] [time], we would have finished."),
    ("What if I need an extension?", "Just ask; [should] [you] [need] [more] [time], the office can help."),
    ("Was the trip ever in doubt?", "Certainly; [were] [it] [not] [for] [her] [passport], we would have cancelled."),
    ("Why did the talk go so well?", "Simply put, [had] [he] [not] [rehearsed] [so] [carefully], it would have failed."),
    ("Do I have to decide tonight?", "No; [should] [you] [prefer] [to] [wait] [a] day, nobody will mind."),
    ("Would the result have changed?", "Probably; [had] [the] [sample] [been] [larger], the effect would have shown."),
    ("Is the grant secure?", "Barely; [were] [the] [sponsor] [to] [withdraw], the lab would close."),
    ("Why was the flight so cheap?", "Apparently, [had] [we] [booked] [a] [week] [later], it would have doubled."),
    ("Can I still join the trip?", "Yes; [should] [a] [place] [become] [available], I will tell you."),
    ("Did anyone predict the failure?", "Nobody did; [had] [the] [warning] [been] [read], nothing would have broken."),
    ("What if the weather turns?", "Relax; [were] [it] [to] [rain] [tomorrow], we would move indoors."),
    ("Why is she so far ahead?", "Simply, [had] [she] [started] [any] [later], she would be behind."),
    ("Is the deadline negotiable?", "Occasionally; [should] [the] [committee] [agree] [in] [writing], an extension is possible."),
    ("Would you have taken the job?", "Certainly; [had] [the] [offer] [come] [in] [spring], I would have accepted."),
    ("Was the evacuation necessary?", "Absolutely; [were] [the] [river] [to] [rise] [further], the road would flood."),
    ("Why did the deal collapse?", "Put simply, [had] [either] [side] [compromised] [slightly], it would have held."),
    ("Can the equipment be replaced?", "Possibly; [should] [the] [budget] [allow] [it], we will order more."),
    ("Did the delay matter?", "Enormously; [had] [the] [parts] [shipped] [on] [schedule], we would have launched."),
    ("What if nobody signs up?", "Well, [were] [attendance] [to] [fall] [below] [ten], the course would close."),
  ]),

dict(
  hard=True,
  target="Mandative subjunctive",
  why="After verbs and adjectives of demand or recommendation the <i>that</i> clause takes the bare base form, with no tense marking and no <i>to</i>: {ans}.",
  extras=["is", "to"],
  items=[
    ("What did the professor insist on?", "She insisted [that] [every] [student] [be] [present] [on] time."),
    ("What did the committee recommend?", "They recommended [that] [the] [proposal] [be] [revised] [before] submission."),
    ("What did he ask for?", "He demanded [that] [his] [name] [be] [removed] [from] the list."),
    ("What was the advice?", "The dean suggested [that] [she] [take] [a] [lighter] [load] next term."),
    ("What did the board decide?", "It was essential [that] [every] [member] [sign] [the] [form] personally."),
    ("What did the doctor say?", "She insisted [that] [he] [rest] [for] [a] [full] week."),
    ("What did the panel require?", "They required [that] [each] [applicant] [submit] [two] [references] in advance."),
    ("What did the union propose?", "They proposed [that] [the] [policy] [be] [reviewed] [every] year."),
    ("What did she request?", "She asked [that] [the] [meeting] [be] [moved] [to] Thursday.", ["is", "was"]),
    ("What is the rule?", "Regulations demand [that] [equipment] [be] [logged] [before] [it] leaves."),
    ("What did the editor insist on?", "He insisted [that] [the] [figures] [be] [checked] [a] second time."),
    ("What did the council urge?", "They urged [that] [construction] [be] [halted] [until] [spring]."),
    ("What did the advisor propose?", "He proposed [that] [I] [defer] [the] [exam] [until] June."),
    ("What does the grant require?", "It requires [that] [results] [be] [published] [within] [two] years."),
    ("What did the chair move?", "She moved [that] [the] [vote] [be] [postponed] [one] week."),
    ("What did the landlord insist?", "He insisted [that] [we] [give] [a] [month's] [notice] first."),
    ("What did the court order?", "It ordered [that] [the] [records] [be] [sealed] [for] a decade."),
    ("What was the recommendation?", "It was vital [that] [nobody] [be] [told] [before] [the] announcement."),
    ("What did the coach demand?", "He demanded [that] [everyone] [arrive] [thirty] [minutes] [early]."),
    ("What did the office suggest?", "They suggested [that] [the] [form] [be] [completed] [online] instead."),
  ]),

dict(
  hard=True,
  target="<i>It</i>-cleft for emphasis",
  why="An <i>it</i>-cleft moves the emphasised element next to <i>it was</i> and puts the rest in a <i>that</i> or <i>who</i> clause: {ans}.",
  extras=["what", "which"],
  items=[
    ("Who actually found the error?", "It [was] [a] [second-year] [student] [who] [spotted] it."),
    ("Was it the data that failed?", "No, it [was] [the] [sensor] [that] [gave] [the] wrong readings."),
    ("Did she choose the topic?", "Actually it [was] [her] [supervisor] [who] [suggested] [it] originally."),
    ("Why is this edition special?", "It [is] [the] [preface] [that] [makes] [this] version valuable."),
    ("What caused the delay?", "It [was] [the] [customs] [check] [that] [held] everything up."),
    ("Did the storm close the road?", "No, it [was] [the] [landslide] [that] [blocked] [the] pass."),
    ("Who paid for the trip?", "It [was] [the] [department] [that] [covered] [the] flights."),
    ("When did she decide?", "It [was] [only] [last] [week] [that] [she] chose."),
    ("What convinced the panel?", "It [was] [the] [fieldwork] [that] [impressed] [them] most."),
    ("Was it the noise?", "No, it [was] [the] [temperature] [that] [ruined] [the] samples."),
    ("Who suggested the change?", "It [was] [a] [junior] [colleague] [who] [raised] it."),
    ("Where did they meet?", "It [was] [in] [the] [archive] [that] [they] first met."),
    ("What does the paper argue?", "It [is] [the] [timing] [that] [the] [author] disputes."),
    ("Did the funding help?", "It [was] [the] [equipment] [that] [made] [the] difference."),
    ("Who wrote the report?", "It [was] [the] [two] [interns] [who] [drafted] it."),
    ("Why did the plan change?", "It [was] [the] [weather] [that] [forced] [the] delay."),
    ("What worried the reviewers?", "It [was] [the] [sample] [size] [that] [troubled] them."),
    ("Did he mention the cost?", "It [was] [the] [schedule] [that] [he] [questioned], not the cost."),
    ("Who runs the seminar?", "It [is] [a] [visiting] [fellow] [who] [leads] it."),
    ("What made the difference?", "It [was] [her] [second] [draft] [that] [won] the prize."),
  ]),

dict(
  hard=True,
  target="Pseudo-cleft with <i>what</i>",
  why="A <i>what</i> clause can serve as the whole subject, with <i>is</i> or <i>was</i> linking it to the emphasised element: {ans}.",
  extras=["that", "which"],
  items=[
    ("Why are you rewriting it?", "What [the] [argument] [needs] [is] [a] [clearer] opening."),
    ("What did the study actually show?", "What [the] [data] [suggest] [is] [that] [temperature] matters most.", ["which", "it"]),
    ("Why did she leave?", "What [she] [wanted] [was] [more] [time] [for] research."),
    ("What went wrong?", "What [surprised] [everyone] [was] [how] [quickly] [it] failed."),
    ("What should I focus on?", "What [matters] [here] [is] [the] [order] [of] the steps."),
    ("Why change the method?", "What [the] [committee] [objected] [to] [was] [the] sampling."),
    ("What impressed the panel?", "What [impressed] [them] [was] [the] [clarity] [of] her answers."),
    ("Why is the section confusing?", "What [the] [chapter] [lacks] [is] [a] [worked] example."),
    ("What did he actually say?", "What [he] [meant] [was] [that] [nobody] [had] checked.", ["which", "it"]),
    ("Why did the plan fail?", "What [nobody] [anticipated] [was] [the] [cost] [of] transport."),
    ("What do you need from me?", "What [would] [help] [most] [is] [a] [second] reader."),
    ("What changed your mind?", "What [convinced] [me] [was] [the] [third] [set] of results."),
    ("What is the real problem?", "What [worries] [me] [is] [the] [missing] [control] group."),
    ("Why did they reject it?", "What [they] [disliked] [was] [the] [tone] [of] the abstract."),
    ("What should we cut?", "What [we] [can] [remove] [is] [the] [historical] section."),
    ("What did the review recommend?", "What [the] [reviewers] [asked] [for] [was] [more] detail."),
    ("Why is she ahead?", "What [she] [does] [differently] [is] [plan] [the] whole term."),
    ("What made the talk work?", "What [held] [the] [room] [was] [the] [opening] anecdote."),
    ("What do you remember most?", "What [stayed] [with] [me] [was] [the] [final] question."),
    ("Why are the results odd?", "What [the] [numbers] [show] [is] [an] [unexpected] pattern."),
  ]),

dict(
  hard=True,
  target="Fronted <i>no sooner</i> and <i>hardly</i>",
  why="<i>No sooner</i>, <i>hardly</i> and <i>scarcely</i> at the front force inversion, and are answered by <i>than</i> or <i>when</i>: {ans}.",
  extras=["then", "as"],
  items=[
    ("Did the rain hold off?", "No sooner [had] [we] [set] [up] [than] [it] poured."),
    ("Was there time to prepare?", "Hardly [had] [I] [opened] [the] [file] [when] the power cut."),
    ("Did she settle in quickly?", "No sooner [had] [she] [arrived] [than] [she] [was] organising everyone."),
    ("Did the news travel?", "Scarcely [had] [the] [email] [gone] [out] [when] the phone rang."),
    ("Was the repair quick?", "No sooner [had] [they] [fixed] [one] [leak] [than] another started."),
    ("Did the meeting run smoothly?", "Hardly [had] [we] [begun] [when] [the] [fire] alarm sounded."),
    ("Did he rest at all?", "No sooner [had] [he] [landed] [than] [he] [went] straight to work."),
    ("Was the queue long?", "Scarcely [had] [I] [joined] [the] [line] [when] it moved."),
    ("Did the storm pass?", "No sooner [had] [the] [wind] [dropped] [than] [the] rain began."),
    ("Did anyone notice?", "Hardly [had] [the] [lights] [dimmed] [when] [the] audience quieted."),
    ("Did they start work?", "No sooner [had] [the] [permit] [arrived] [than] [digging] began."),
    ("Was the book popular?", "Scarcely [had] [it] [appeared] [when] [the] [first] printing sold out."),
    ("Did she reply?", "No sooner [had] [I] [pressed] [send] [than] [she] answered."),
    ("Did the term feel long?", "Hardly [had] [classes] [started] [when] [exams] [were] announced."),
    ("Was the road cleared?", "No sooner [had] [the] [snow] [stopped] [than] [ploughs] appeared."),
    ("Did the crowd settle?", "Scarcely [had] [the] [speaker] [begun] [when] [someone] interrupted."),
    ("Did you get a seat?", "No sooner [had] [the] [doors] [opened] [than] [every] seat filled."),
    ("Was the fault found?", "Hardly [had] [the] [engineer] [looked] [when] [she] saw it."),
    ("Did the price hold?", "No sooner [had] [we] [agreed] [than] [the] [rate] changed."),
    ("Did they finish the season?", "Scarcely [had] [the] [team] [recovered] [when] [injuries] returned."),
  ]),
]
