# -*- coding: utf-8 -*-
"""Causatives, bare infinitives, habit, wishes, advice, deduction, indirect questions."""

PATTERNS = [
dict(
  target="Causative <i>have</i> or <i>get</i> something done",
  why="A causative puts the object before the past participle, because someone else does the work: {ans}.",
  extras=["been"],
  items=[
    ("Your screen looks new.", "I [had] [it] [replaced] [last] Tuesday."),
    ("Did you fix the bike yourself?", "No, I [got] [it] [serviced] [at] the shop."),
    ("Is the form ready?", "I still need to [have] [it] [signed] [by] my advisor."),
    ("Your hair looks different.", "I [had] [it] [cut] [on] Saturday."),
    ("Did you print the poster?", "I [got] [it] [printed] [in] the library."),
    ("Is the essay proofread?", "I [had] [a] [friend] [check] it."),
    ("What about the broken window?", "We're [having] [it] [fixed] [this] week."),
    ("Did you develop the film?", "I [had] [the] [negatives] [scanned] professionally."),
    ("Is the suit ready?", "I [got] [it] [altered] [yesterday] afternoon."),
    ("Did you write the translation?", "I [had] [it] [translated] [by] a specialist."),
    ("What about the leaking tap?", "I'll [get] [it] [repaired] [before] the weekend."),
    ("Is your passport renewed?", "I [had] [it] [renewed] [in] March."),
    ("Did you take the photos?", "I [had] [them] [taken] [at] a studio."),
    ("What about the car noise?", "I'm [getting] [it] [checked] [on] Thursday."),
    ("Is the data cleaned?", "We [had] [it] [processed] [by] the lab."),
    ("Did you make the shelves?", "I [got] [them] [built] [to] measure."),
    ("What about the old photographs?", "I [had] [them] [digitized] [last] summer."),
    ("Is the contract final?", "We need to [have] [it] [reviewed] [first]."),
    ("Did you clean the carpet?", "I [got] [it] [cleaned] [professionally] instead."),
    ("What about the garden?", "We [have] [it] [maintained] [every] spring."),
  ]),

dict(
  target="<i>Make</i> and <i>let</i> with a bare infinitive",
  why="<i>Make</i> and <i>let</i> take an object followed by a bare infinitive, with no <i>to</i>: {ans}.",
  extras=["to"],
  items=[
    ("Did the professor allow extensions?", "She [let] [us] [hand] [it] in late."),
    ("Why did you rewrite it?", "My advisor [made] [me] [start] [again] from scratch."),
    ("Did they let you in?", "The guard [let] [me] [wait] [in] the lobby."),
    ("Why are you here so early?", "My coach [makes] [us] [arrive] [before] dawn."),
    ("Did she explain the change?", "She [let] [the] [group] [decide] together."),
    ("Why did you stay up?", "The deadline [made] [me] [work] [through] the night."),
    ("Did they allow photographs?", "They [let] [visitors] [take] [pictures] outside only."),
    ("Why did you cut the section?", "The editor [made] [me] [remove] [two] pages."),
    ("Did the landlord agree?", "He [let] [us] [paint] [the] kitchen."),
    ("Why is everyone laughing?", "Her story [made] [us] [laugh] [for] ten minutes."),
    ("Did the office help?", "They [let] [me] [register] [after] the deadline."),
    ("Why did you change labs?", "My supervisor [made] [me] [choose] [a] new project."),
    ("Did they permit questions?", "The chair [let] [the] [audience] [ask] two."),
    ("Why were you late?", "Security [made] [everyone] [empty] [their] bags."),
    ("Did she share the notes?", "She [let] [me] [copy] [the] whole set."),
    ("Why did you apologize?", "My conscience [made] [me] [write] [to] her."),
    ("Did the tutor give feedback?", "He [let] [me] [read] [his] comments first."),
    ("Why did you miss the bus?", "The traffic [made] [us] [wait] [twenty] minutes."),
    ("Did they allow food?", "They [let] [people] [bring] [their] own lunch."),
    ("Why did you stop running?", "The heat [made] [me] [slow] [right] down."),
  ]),

dict(
  target="<i>Used to</i> and <i>be used to</i>",
  why="<i>Used to</i> plus a base verb names a discontinued past habit, while <i>be used to</i> plus a gerund or noun means accustomed to something: {ans}.",
  extras=["use"],
  items=[
    ("Do you still swim daily?", "I [used] [to] [swim] [every] morning."),
    ("Is the early start hard?", "I'm [used] [to] [waking] [before] five now."),
    ("Did you live here before?", "I [used] [to] [rent] [a] room nearby."),
    ("Does the noise bother you?", "I've [grown] [used] [to] [it]."),
    ("Do you still play chess?", "I [used] [to] [play] [every] weekend."),
    ("Is the workload manageable?", "I'm [getting] [used] [to] [the] pace."),
    ("Did she teach here?", "She [used] [to] [lecture] [in] this building."),
    ("Is the commute tiring?", "I'm [used] [to] [standing] [the] whole way."),
    ("Did the place serve breakfast?", "It [used] [to] [open] [at] six."),
    ("Does the cold trouble you?", "I'm [not] [used] [to] [winters] like this."),
    ("Did you write by hand?", "I [used] [to] [draft] [everything] on paper."),
    ("Is the software confusing?", "I'm [still] [not] [used] [to] the layout."),
    ("Did they meet weekly?", "The group [used] [to] [gather] [on] Fridays."),
    ("Is public speaking easier now?", "I'm [used] [to] [addressing] [large] rooms."),
    ("Did the library close early?", "It [used] [to] [shut] [at] nine."),
    ("Does the altitude affect you?", "I'm [not] [used] [to] [thin] air."),
    ("Did you take the bus?", "I [used] [to] [cycle] [instead]."),
    ("Is the accent hard to follow?", "I'm [becoming] [used] [to] [it] slowly."),
    ("Did he coach the team?", "He [used] [to] [train] [the] juniors."),
    ("Does night work suit you?", "I'm [quite] [used] [to] [late] shifts."),
  ]),

dict(
  target="<i>Wish</i> about the present",
  why="A wish about the present takes a past form, and <i>were</i> for every subject: {ans}.",
  extras=["will"],
  items=[
    ("Can you come to the concert?", "I [wish] [I] [had] [more] free time."),
    ("Do you like the apartment?", "I [wish] [it] [were] [closer] to campus."),
    ("Is the course going well?", "I [wish] [I] [understood] [the] statistics better."),
    ("Are you enjoying the weather?", "I [wish] [it] [would] [stop] raining."),
    ("Do you speak Portuguese?", "I [wish] [I] [spoke] [it] fluently."),
    ("Is the group working well?", "I [wish] [we] [met] [more] often."),
    ("Is your handwriting always like that?", "I [wish] [my] [handwriting] [were] clearer."),
    ("Is the job stressful?", "I [wish] [the] [hours] [were] shorter."),
    ("Can you join us tonight?", "I [wish] [I] [weren't] [so] tired."),
    ("Do you like the new system?", "I [wish] [it] [worked] [more] reliably."),
    ("Is the room warm enough?", "I [wish] [the] [heating] [came] on earlier."),
    ("Do you know the answer?", "I [wish] [I] [knew] [the] answer."),
    ("Are you ready for the talk?", "I [wish] [I] [felt] [more] confident."),
    ("Is the flat noisy?", "I [wish] [the] [neighbors] [were] quieter."),
    ("Do you see her often?", "I [wish] [she] [lived] [nearby]."),
    ("Is the deadline realistic?", "I [wish] [we] [had] [another] week."),
    ("Do you enjoy the commute?", "I [wish] [the] [train] [ran] more often."),
    ("Are the seats comfortable?", "I [wish] [they] [reclined] [a] little."),
    ("Is the food good?", "I [wish] [there] [were] [more] choice."),
    ("Do you get enough sleep?", "I [wish] [I] [slept] [through] the night."),
  ]),

dict(
  target="<i>Wish</i> about the past",
  why="A regret about the past takes <i>wish</i> plus the past perfect: {ans}.",
  extras=["would"],
  items=[
    ("Did you take the elective?", "I [wish] [I] [had] [signed] up for it."),
    ("Were you at the lecture?", "I [wish] [I] [had] [gone] to it."),
    ("Did you keep the receipt?", "I [wish] [I] [had] [kept] it."),
    ("Did you apply last year?", "I [wish] [I] [had] [applied] earlier."),
    ("Was the trip worthwhile?", "I [wish] [we] [had] [stayed] longer."),
    ("Did you study abroad?", "I [wish] [I] [had] [taken] the chance."),
    ("Did anyone warn you?", "I [wish] [someone] [had] [mentioned] the change."),
    ("Did you back up the file?", "I [wish] [I] [had] [saved] a copy."),
    ("Were you nervous?", "I [wish] [I] [had] [practiced] more beforehand."),
    ("Did you meet the author?", "I [wish] [I] [had] [asked] her a question."),
    ("Did you buy the tickets?", "I [wish] [we] [had] [booked] them sooner."),
    ("Did he tell you?", "I [wish] [he] [had] [said] something earlier."),
    ("Did you take the photos?", "I [wish] [I] [had] [brought] my camera."),
    ("Was the route difficult?", "I [wish] [we] [had] [checked] the map."),
    ("Did you finish the reading?", "I [wish] [I] [had] [started] on Monday."),
    ("Did she get your message?", "I [wish] [I] [had] [called] instead."),
    ("Was the seminar useful?", "I [wish] [I] [had] [attended] all of them."),
    ("Did you keep in touch?", "I [wish] [we] [had] [written] more often."),
    ("Did you see the exhibition?", "I [wish] [I] [had] [visited] before it closed."),
    ("Was the advice helpful?", "I [wish] [I] [had] [listened] to it."),
  ]),

dict(
  target="<i>Had better</i> and <i>would rather</i>",
  why="Both <i>had better</i> and <i>would rather</i> are followed by a bare infinitive, with no <i>to</i>: {ans}.",
  extras=["to"],
  items=[
    ("Should I hand it in now?", "You [had] [better] [submit] [it] today."),
    ("Do you want to go out?", "I [would] [rather] [stay] [in] tonight."),
    ("Shall we take the car?", "We [had] [better] [walk] [in] this traffic."),
    ("Coffee or tea?", "I [would] [rather] [have] [tea], thanks."),
    ("Should I email the professor?", "You [had] [better] [ask] [her] directly."),
    ("Do you mind presenting first?", "I [would] [rather] [go] [last] if possible."),
    ("Should we wait for them?", "We [had] [better] [start] [without] them."),
    ("Want to watch a film?", "I [would] [rather] [finish] [this] chapter."),
    ("Should I book now?", "You [had] [better] [reserve] [a] seat early."),
    ("Shall we meet at noon?", "I [would] [rather] [meet] [after] lunch."),
    ("Should I bring a coat?", "You [had] [better] [take] [one] along."),
    ("Do you want to drive?", "I [would] [rather] [take] [the] train."),
    ("Should we tell the group?", "We [had] [better] [explain] [it] tomorrow."),
    ("Want to join the trip?", "I [would] [rather] [save] [the] money."),
    ("Should I revise tonight?", "You [had] [better] [sleep] [instead]."),
    ("Shall I call her?", "I [would] [rather] [you] [called] her."),
    ("Should we cancel?", "We [had] [better] [postpone] [than] cancel."),
    ("Do you want the aisle seat?", "I [would] [rather] [sit] [by] the window."),
    ("Should I print the slides?", "You [had] [better] [bring] [a] backup."),
    ("Shall we eat now?", "I [would] [rather] [wait] [a] while."),
  ]),

dict(
  target="Modal of deduction about the past",
  why="A deduction about the past takes a modal plus <i>have</i> plus a past participle: {ans}.",
  extras=["did"],
  items=[
    ("Why is the door open?", "Someone [must] [have] [forgotten] [to] lock it."),
    ("She didn't reply.", "She [can't] [have] [seen] [the] message."),
    ("The lights are off.", "They [must] [have] [left] [already]."),
    ("He looks exhausted.", "He [might] [have] [worked] [all] night."),
    ("The file is missing.", "It [may] [have] [been] [deleted] by accident."),
    ("She passed easily.", "She [must] [have] [studied] [for] weeks."),
    ("The road is wet.", "It [must] [have] [rained] [overnight]."),
    ("He never mentioned it.", "He [can't] [have] [known] [about] the change."),
    ("The window is broken.", "A branch [could] [have] [hit] [it]."),
    ("They arrived very early.", "They [must] [have] [taken] [the] first train."),
    ("The report is incomplete.", "She [might] [have] [run] [out] of time."),
    ("Nobody answered.", "They [may] [have] [gone] [out]."),
    ("The results look odd.", "The sensor [must] [have] [malfunctioned] [again]."),
    ("He seemed surprised.", "Nobody [can] [have] [told] [him] beforehand."),
    ("The plant died.", "It [might] [have] [needed] [more] light."),
    ("She knew the answer instantly.", "She [must] [have] [read] [the] chapter."),
    ("The room was spotless.", "Someone [must] [have] [cleaned] [it] early."),
    ("My keys are gone.", "You [could] [have] [dropped] [them] outside."),
    ("The talk ended early.", "The speaker [may] [have] [fallen] [ill]."),
    ("They looked confused.", "We [can't] [have] [explained] [it] clearly."),
  ]),

dict(
  target="Indirect polite question",
  why="A question folded inside a polite request keeps statement word order after the question word: {ans}.",
  extras=["does"],
  items=[
    ("I'm looking for the registrar.", "Could you tell me [where] [the] [office] [is] located?"),
    ("The train times changed.", "Do you know [when] [the] [next] [one] leaves?"),
    ("I can't find the form.", "Could you show me [where] [it] [is] [kept]?"),
    ("The lecture moved rooms.", "Do you know [which] [room] [they] [use] now?"),
    ("I need the reading list.", "Can you tell me [where] [I] [can] [find] it?"),
    ("The fee went up.", "Do you know [how] [much] [it] [costs] now?"),
    ("She left a message.", "Did she say [when] [she] [would] [call] back?"),
    ("The library moved the journals.", "Could you tell me [which] [floor] [they] [are] on?"),
    ("I missed the announcement.", "Do you know [what] [the] [dean] [said]?"),
    ("The bus route changed.", "Can you tell me [where] [it] [stops] [now]?"),
    ("The deadline is unclear.", "Do you know [when] [the] [essay] [is] due?"),
    ("I need to reach the lab.", "Could you tell me [how] [I] [get] [there]?"),
    ("The password expired.", "Do you know [who] [resets] [these] [accounts]?"),
    ("The seminar has a reading.", "Can you tell me [which] [chapter] [we] [need]?"),
    ("The office hours shifted.", "Do you know [what] [time] [she] [starts] now?"),
    ("I lost the syllabus.", "Could you tell me [where] [it] [was] [posted]?"),
    ("The exam format changed.", "Do you know [how] [long] [the] [paper] is?"),
    ("There's a new printer.", "Can you tell me [how] [this] [machine] [works]?"),
    ("The grant has a deadline.", "Do you know [when] [applications] [close] [this] year?"),
    ("The hall was locked.", "Could you tell me [who] [has] [the] [key]?"),
  ]),
]
