# -*- coding: utf-8 -*-
"""Embedded questions, reported speech, verb complements, perfect aspect."""

PATTERNS = [
dict(
  target="Word order in an embedded question",
  why="An embedded question keeps statement word order &mdash; {ans} &mdash; because the auxiliary of a direct question belongs only to a direct question.",
  extras=["did"],
  items=[
    ("Did the advisor say anything about the deadline?", "She asked [when] [I] [planned] [to] [submit] the application."),
    ("What did the professor want at the end of class?", "He wanted to know [why] [my] [group] [had] [changed] topics."),
    ("Did the coach talk to you after practice?", "Yes, he asked [how] [long] [I] [had] [been] swimming competitively."),
    ("What did the librarian say?", "She asked [which] [journals] [I] [still] [needed] for the paper."),
    ("Did your tutor mention the exam?", "She asked [where] [the] [review] [session] [would] be held."),
    ("What did your roommate want?", "He asked [whose] [notes] [I] [had] [borrowed] last week."),
    ("Did anyone ask about the field trip?", "A few people asked [what] [time] [the] [bus] [leaves] on Saturday."),
    ("Did the counselor follow up with you?", "She asked [how] [many] [credits] [I] [had] finished so far."),
    ("What did the professor say about your draft?", "He asked [why] [I] [had] [chosen] [such] a narrow topic."),
    ("Did your lab partner text you?", "She asked [when] [we] [should] [start] [the] second trial."),
    ("What did the manager want to know?", "He asked [how] [often] [I] [could] [work] weekend shifts."),
    ("Did the host family ask about your plans?", "They asked [where] [I] [wanted] [to] [travel] in the spring."),
    ("Did anyone question the results?", "One student asked [what] [the] [control] [group] [was] measuring."),
    ("What did your advisor ask about?", "She asked [which] [electives] [I] [was] [considering] for next term."),
    ("Did the trainer say anything?", "He asked [how] [much] [sleep] [I] [had] been getting."),
    ("What did the interviewer ask first?", "She asked [why] [I] [had] [applied] [to] this program."),
    ("Did your neighbor come by?", "He asked [when] [the] [building] [inspection] [was] scheduled."),
    ("What did the RA announce?", "She explained [how] [the] [new] [laundry] [cards] work."),
    ("Did the professor respond to your email?", "He asked [what] [chapter] [I] [was] [having] trouble with."),
    ("Did the office call you back?", "They asked [which] [form] [I] [had] [already] submitted."),
  ]),

dict(
  target="Embedded yes/no question with <i>whether</i>",
  why="A yes/no question embedded inside a statement is introduced by <i>whether</i> or <i>if</i> and keeps statement word order: {ans}.",
  extras=["do"],
  items=[
    ("Is the writing center open on Sundays?", "I'm not sure [whether] [it] [opens] [before] [noon] on weekends."),
    ("Will the lecture be recorded?", "I asked [whether] [the] [session] [would] [be] posted online."),
    ("Can we bring laptops to the exam?", "Nobody knows [if] [we] [are] [allowed] [to] use them."),
    ("Did the package arrive?", "I can't tell [whether] [anyone] [signed] [for] [it] this morning."),
    ("Is the shuttle running today?", "Let me check [whether] [it] [stops] [at] [the] north gate."),
    ("Should I register now?", "It depends on [whether] [the] [course] [still] [has] open seats."),
    ("Has the grant been approved?", "No one has said [whether] [the] [committee] [has] [made] a decision."),
    ("Are you joining the trip?", "I haven't decided [whether] [I] [can] [afford] [the] extra week."),
    ("Did she get the internship?", "She didn't mention [whether] [the] [offer] [had] [come] through."),
    ("Is the gym closed for repairs?", "The sign doesn't say [whether] [the] [pool] [is] [closed] too."),
    ("Will the deadline move?", "I wonder [whether] [they] [will] [extend] [it] another week."),
    ("Can I take both seminars?", "Ask the registrar [whether] [the] [times] [actually] [overlap] this term."),
    ("Is parking free after six?", "I'm not certain [whether] [the] [meters] [run] [that] late."),
    ("Did he finish the reading?", "He wouldn't say [whether] [he] [had] [even] [started] it."),
    ("Are the results posted?", "I'll find out [whether] [the] [scores] [went] [up] today."),
    ("Is this seat taken?", "I don't know [whether] [anyone] [is] [sitting] [here] right now."),
    ("Will the tutor come tonight?", "She hasn't confirmed [whether] [she] [can] [make] [it] at seven."),
    ("Do I need a visa for the conference?", "Check [whether] [your] [passport] [is] [still] valid first."),
    ("Was the talk any good?", "I can't say [whether] [it] [was] [worth] [the] trip."),
    ("Is the caf&eacute; hiring?", "I'll ask [whether] [they] [need] [anyone] [for] mornings."),
  ]),

dict(
  target="Backshift in reported speech",
  why="After a past reporting verb such as <i>said</i>, <i>will</i> backshifts to <i>would</i>: {ans}.",
  extras=["will"],
  items=[
    ("What did the librarian tell you?", "She said [that] [the] [book] [would] [be] held until Friday."),
    ("What did your advisor say about the form?", "He said [it] [would] [take] [about] [ten] days to process."),
    ("Did the office reply?", "They said [someone] [would] [call] [me] [back] this afternoon."),
    ("What did the professor announce?", "She said [the] [midterm] [would] [cover] [three] chapters."),
    ("Did the coach say anything about Saturday?", "He said [practice] [would] [start] [an] [hour] earlier."),
    ("What did the landlord tell you?", "He said [the] [heat] [would] [be] [fixed] by Thursday."),
    ("Did they explain the delay?", "They said [the] [shipment] [would] [arrive] [late] next week."),
    ("What did your tutor promise?", "She said [she] [would] [look] [at] [my] draft tonight."),
    ("Did the TA mention the curve?", "He said [the] [grades] [would] [go] [up] slightly."),
    ("What did the doctor say?", "She said [the] [results] [would] [take] [a] few days."),
    ("Did the airline update you?", "They said [the] [flight] [would] [board] [at] gate twelve."),
    ("What did the committee decide?", "They said [a] [decision] [would] [come] [by] the end of term."),
    ("Did she say when she is leaving?", "She said [she] [would] [move] [out] [in] June."),
    ("What did the technician tell you?", "He said [the] [projector] [would] [need] [a] new bulb."),
    ("Did the bank explain the fee?", "They said [the] [charge] [would] [be] [refunded] automatically."),
    ("What did your group decide?", "They said [we] [would] [meet] [in] [the] library at six."),
    ("Did the professor respond?", "He said [he] [would] [post] [the] [slides] after class."),
    ("What did the RA say about quiet hours?", "She said [they] [would] [begin] [at] [ten] on weeknights."),
    ("Did the store call?", "They said [the] [part] [would] [be] [in] on Monday."),
    ("What did the office say about housing?", "They said [assignments] [would] [go] [out] [in] August."),
  ]),

dict(
  target="Infinitive complement",
  why="This verb takes an infinitive rather than a gerund: {ans}.",
  items=[
    ("I didn't see you at office hours yesterday.", "I [meant] [to] [stop] [by] but my lab ran late.", ["stopping"]),
    ("Are you coming to the study group?", "I [decided] [to] [join] [the] second session instead.", ["joining"]),
    ("Did you sign up for the trip?", "I [offered] [to] [drive] [the] van if nobody else could.", ["driving"]),
    ("Why is your essay late?", "I [forgot] [to] [attach] [the] file to my email.", ["attaching"]),
    ("Will you take the advanced section?", "I [hope] [to] [place] [into] it next term.", ["placing"]),
    ("Did he apologize?", "He [refused] [to] [admit] [that] he was wrong.", ["admitting"]),
    ("Are you still on the committee?", "I [agreed] [to] [stay] [for] one more year.", ["staying"]),
    ("How did the presentation go?", "We [managed] [to] [finish] [with] two minutes left.", ["finishing"]),
    ("Is she transferring?", "She [plans] [to] [apply] [in] the fall.", ["applying"]),
    ("Did you get the scholarship?", "I [failed] [to] [meet] [the] March deadline.", ["meeting"]),
    ("Why didn't you call?", "I [tried] [to] [reach] [you] twice last night.", ["reaching"]),
    ("Are you going to the lecture?", "I [intend] [to] [go] [if] the rain stops.", ["going"]),
    ("Did they fix the schedule?", "They [promised] [to] [post] [it] before registration.", ["posting"]),
    ("Is he joining the lab?", "He [wants] [to] [work] [on] the imaging project.", ["working"]),
    ("Did you talk to the dean?", "I [arranged] [to] [see] [her] on Thursday.", ["seeing"]),
    ("Are you taking a gap year?", "I [chose] [to] [defer] [for] two semesters.", ["deferring"]),
    ("Why the change of topic?", "I [needed] [to] [narrow] [the] question considerably.", ["narrowing"]),
    ("Did she accept the offer?", "She [seems] [to] [prefer] [the] other program.", ["preferring"]),
    ("How is the group project going?", "We [expect] [to] [submit] [it] by Sunday.", ["submitting"]),
    ("Did you renew the book?", "I [forgot] [to] [return] [it] on time.", ["returning"]),
  ]),

dict(
  target="Gerund complement",
  why="This verb takes a gerund rather than an infinitive: {ans}.",
  items=[
    ("Have you dropped the class?", "I [considered] [dropping] [it] [after] the first exam.", ["to drop"]),
    ("You still run every morning?", "I [keep] [putting] [it] [off] until the weekend.", ["to put"]),
    ("Did you finish the reading?", "I [finished] [annotating] [the] [second] chapter last night.", ["to annotate"]),
    ("Why not take the early train?", "I [avoid] [traveling] [before] [seven] if I can.", ["to travel"]),
    ("Should we move the meeting?", "I [suggest] [starting] [an] [hour] later.", ["to start"]),
    ("Do you mind the noise?", "I [don't] [mind] [working] [with] music on.", ["to work"]),
    ("Are you still tutoring?", "I [enjoy] [helping] [the] [first-year] students.", ["to help"]),
    ("Did she quit the team?", "She [gave] [up] [competing] [after] the injury.", ["to compete"]),
    ("Is the printer working?", "It [stopped] [feeding] [paper] [halfway] through.", ["to feed"]),
    ("Have you decided on a topic?", "I [put] [off] [choosing] [one] until yesterday.", ["to choose"]),
    ("Why the late night?", "I [couldn't] [risk] [missing] [the] deadline.", ["to miss"]),
    ("Do you still take the bus?", "I [prefer] [walking] [when] [the] weather holds.", ["to walk"]),
    ("Did he explain himself?", "He [denied] [seeing] [the] [email] at all.", ["to see"]),
    ("Are you going to the recital?", "I'm [looking] [forward] [to] [hearing] her play.", ["hear"]),
    ("Is the essay done?", "I [postponed] [editing] [it] [until] this evening.", ["to edit"]),
    ("Did you try the new caf&eacute;?", "I [recommend] [getting] [there] [before] the rush.", ["to get"]),
    ("Are you still in the choir?", "I [quit] [attending] [after] [the] fall concert.", ["to attend"]),
    ("Why did the demo fail?", "We [delayed] [testing] [the] [build] until too late.", ["to test"]),
    ("Do you read before bed?", "I [practice] [reading] [something] [unrelated] to my field.", ["to read"]),
    ("Did they cancel the trip?", "They [discussed] [postponing] [it] [for] a month.", ["to postpone"]),
  ]),

dict(
  target="Gerund after a preposition",
  why="A preposition must be followed by a gerund, never an infinitive: {ans}.",
  items=[
    ("How did the firm grow so fast?", "They [attribute] [it] [to] [investing] [in] training.", ["invest"]),
    ("Why are you so tired?", "I'm [used] [to] [getting] [up] [before] five now.", ["get"]),
    ("Did you thank her?", "I thanked her [for] [reading] [my] [draft] twice.", ["to read"]),
    ("How did you pass?", "I passed [by] [reviewing] [every] [problem] set.", ["to review"]),
    ("Are you nervous about Friday?", "I'm [worried] [about] [forgetting] [my] opening line.", ["forget"]),
    ("Why the new route?", "I [insist] [on] [leaving] [before] traffic builds.", ["leave"]),
    ("Did he apologize?", "He apologized [for] [missing] [the] [group] meeting.", ["to miss"]),
    ("Is she good at presentations?", "She's [good] [at] [explaining] [difficult] ideas simply.", ["explain"]),
    ("How do you stay focused?", "I [succeed] [by] [breaking] [the] work into blocks.", ["to break"]),
    ("Why not ask for help?", "I'm [capable] [of] [figuring] [it] out myself.", ["figure"]),
    ("Did they object?", "They [objected] [to] [moving] [the] deadline again.", ["move"]),
    ("Are you ready for the exam?", "I'm [tired] [of] [rereading] [the] same chapter.", ["reread"]),
    ("How did you find the internship?", "I [succeeded] [in] [reaching] [an] alumnus directly.", ["to reach"]),
    ("Why skip the lecture?", "There's no [point] [in] [going] [without] the reading.", ["to go"]),
    ("Did you enjoy the seminar?", "I [look] [forward] [to] [attending] again.", ["attend"]),
    ("How is the new job?", "I'm [getting] [used] [to] [answering] so many emails.", ["answer"]),
    ("Did she agree?", "She [agreed] [without] [hearing] [the] whole proposal.", ["to hear"]),
    ("Why the early start?", "I [believe] [in] [finishing] [before] noon.", ["to finish"]),
    ("Are you still worried?", "I'm [afraid] [of] [running] [out] of time.", ["run"]),
    ("How did you learn so fast?", "I [improved] [by] [practicing] [every] single day.", ["to practice"]),
  ]),

dict(
  target="Present perfect with <i>since</i> or <i>for</i>",
  why="A situation that began in the past and still continues takes the present perfect: {ans}.",
  items=[
    ("How long have you been on the swim team?", "I [have] [been] [part] [of] the team since my first year.", ["am"]),
    ("Do you know this neighborhood?", "I [have] [lived] [here] [for] almost four years.", ["live"]),
    ("Is he still your advisor?", "He [has] [supervised] [my] [work] since last spring.", ["supervises"]),
    ("How long has the lab been closed?", "It [has] [been] [shut] [since] the flood.", ["is"]),
    ("Do you still play?", "I [haven't] [touched] [the] [piano] since August.", ["didn't"]),
    ("Is the position still open?", "They [have] [been] [interviewing] [for] two months.", ["are"]),
    ("How long have you known her?", "We [have] [been] [friends] [since] orientation week.", ["are"]),
    ("Are you new to the city?", "I [have] [only] [been] [here] for a semester.", ["was"]),
    ("Is the renovation finished?", "The crew [has] [worked] [on] [it] since June.", ["works"]),
    ("Do you still volunteer there?", "I [have] [helped] [out] [every] Saturday since March.", ["help"]),
    ("How long has he taught here?", "He [has] [been] [teaching] [here] for a decade.", ["is"]),
    ("Is the caf&eacute; new?", "It [has] [been] [open] [since] the start of term.", ["is"]),
    ("Do you still use that laptop?", "I [have] [had] [it] [since] high school.", ["having"]),
    ("Are they still in the program?", "They [have] [stayed] [in] [it] for three terms.", ["stay"]),
    ("Is she still recovering?", "She [has] [been] [resting] [since] the surgery.", ["was"]),
    ("How long has the road been closed?", "It [has] [been] [blocked] [for] several weeks.", ["was"]),
    ("Do you follow that research?", "I [have] [read] [her] [papers] since undergrad.", ["reads"]),
    ("Is the club still active?", "It [has] [met] [every] [month] since 2019.", ["meets"]),
    ("Are you still on that project?", "I [have] [worked] [on] [it] since January.", ["work"]),
    ("Has the policy changed?", "It [has] [stayed] [the] [same] for years.", ["stays"]),
  ]),

dict(
  target="Past perfect for the earlier past event",
  why="When one past event precedes another, the earlier one takes the past perfect: {ans}.",
  extras=["has"],
  items=[
    ("Why didn't you get a seat?", "The lecture [had] [already] [started] [when] I arrived."),
    ("Did you see the announcement?", "They [had] [posted] [it] [before] I woke up."),
    ("Why was the exam so easy?", "I [had] [reviewed] [every] [chapter] the night before."),
    ("Did she make the train?", "It [had] [left] [by] [the] time she got there."),
    ("Was the room still free?", "Someone [had] [booked] [it] [an] hour earlier."),
    ("Why did the demo fail?", "We [had] [forgotten] [to] [install] the update."),
    ("Did he know about the change?", "Nobody [had] [told] [him] [before] the meeting."),
    ("Was the article useful?", "I [had] [read] [it] [long] before the seminar."),
    ("Why were you surprised?", "She [had] [never] [mentioned] [the] transfer to me."),
    ("Did they finish on time?", "They [had] [completed] [the] [survey] before the deadline."),
    ("Was the food gone?", "The other group [had] [eaten] [most] [of] it already."),
    ("Why did you change advisors?", "Mine [had] [moved] [to] [another] university."),
    ("Did the package arrive?", "It [had] [been] [delivered] [to] the wrong address."),
    ("Were you prepared?", "I [had] [practiced] [the] [talk] four times."),
    ("Why was the lab locked?", "The technician [had] [gone] [home] [before] five."),
    ("Did you recognize her?", "We [had] [met] [once] [at] a conference."),
    ("Was the deadline extended?", "They [had] [announced] [it] [the] previous week."),
    ("Why didn't you answer?", "My phone [had] [died] [during] [the] afternoon."),
    ("Did she get the notes?", "I [had] [sent] [them] [before] class started."),
    ("Was the store open?", "It [had] [closed] [twenty] [minutes] earlier."),
  ]),
]
