# -*- coding: utf-8 -*-
"""HARD tier: only-inversion, formal than-clauses, locative inversion, one-of agreement, clausal objects."""

PATTERNS = [
dict(
  hard=True,
  target="Inversion after fronted <i>only</i>",
  why="A fronted <i>only</i> phrase pushes the auxiliary in front of the subject of the main clause, while the <i>only</i> clause itself keeps normal order: {ans}.",
  extras=["that", "so"],
  items=[
    ("When did you realise the error?", "Only when [the] [results] [came] [back] [did] [we] understand."),
    ("When did she agree?", "Only after [the] [contract] [was] [revised] [did] [she] sign."),
    ("When did the funding arrive?", "Only in [the] [second] [year] [did] [the] [money] appear."),
    ("When did they notice?", "Only then [did] [anyone] [check] [the] [original] [readings]."),
    ("When was the fault found?", "Only during [the] [final] [test] [did] [the] [fault] appear."),
    ("When did he apologise?", "Only after [a] [week] [had] [passed] [did] [he] write."),
    ("When did the crowd settle?", "Only when [the] [lights] [dimmed] [did] [the] [noise] stop."),
    ("When did she publish?", "Only much [later] [did] [she] [release] [the] [full] dataset."),
    ("When did the road reopen?", "Only after [the] [inspection] [was] [complete] [did] [traffic] resume."),
    ("When did you understand it?", "Only on [the] [third] [reading] [did] [the] [argument] make sense."),
    ("When did they respond?", "Only when [we] [phoned] [twice] [did] [anyone] [reply]."),
    ("When did the pattern emerge?", "Only after [months] [of] [sampling] [did] [a] [pattern] emerge."),
    ("When was the error corrected?", "Only in [the] [reprint] [was] [the] [figure] [finally] fixed."),
    ("When did she take the lead?", "Only when [the] [chair] [resigned] [did] [she] [step] forward."),
    ("When did it become clear?", "Only by [comparing] [both] [drafts] [did] [we] [see] it."),
    ("When did the price drop?", "Only after [supply] [recovered] [fully] [did] [prices] [fall]."),
    ("When did the team improve?", "Only once [the] [new] [coach] [arrived] [did] [results] improve."),
    ("When did you get the email?", "Only this [morning] [did] [the] [notice] [finally] [arrive]."),
    ("When did they admit it?", "Only under [questioning] [did] [the] [firm] [accept] [responsibility]."),
    ("When did the rain stop?", "Only towards [dawn] [did] [the] [storm] [finally] [ease]."),
  ]),

dict(
  hard=True,
  target="Comparative with an elliptical <i>than</i> clause",
  why="A formal <i>than</i> clause can leave out the repeated element entirely, keeping only what contrasts: {ans}.",
  extras=["as", "that"],
  items=[
    ("Was the turnout good?", "Attendance [was] [far] [higher] [than] [had] [been] anticipated."),
    ("Did the repair cost much?", "It [cost] [rather] [more] [than] [we] [had] budgeted."),
    ("Was the paper long?", "It [ran] [considerably] [longer] [than] [the] [editor] wanted."),
    ("Did the trial take long?", "It [took] [twice] [as] [long] [as] [anyone] expected.", ["than", "so"]),
    ("Was the effect large?", "The effect [proved] [smaller] [than] [earlier] [work] [had] suggested."),
    ("Did many attend?", "Fewer [came] [than] [the] [organisers] [had] [hoped]."),
    ("Was the winter severe?", "It [was] [harsher] [than] [any] [on] [record]."),
    ("Did the fund grow?", "It [grew] [more] [slowly] [than] [the] [trustees] intended."),
    ("Was the estimate accurate?", "The figure [was] [lower] [than] [the] [survey] [implied]."),
    ("Did the talk overrun?", "It [lasted] [longer] [than] [the] [schedule] [allowed]."),
    ("Was the response good?", "Replies [arrived] [faster] [than] [we] [had] [dared] hope."),
    ("Did the costs rise?", "They [rose] [more] [sharply] [than] [the] [forecast] predicted."),
    ("Was the sample big enough?", "It [was] [smaller] [than] [good] [practice] [requires]."),
    ("Did the ice retreat?", "It [retreated] [further] [than] [it] [had] [in] decades."),
    ("Was the book successful?", "It [sold] [better] [than] [the] [publisher] [had] expected."),
    ("Did the delay hurt?", "It [proved] [less] [damaging] [than] [everyone] [feared]."),
    ("Was the result reproducible?", "It [proved] [harder] [to] [repeat] [than] [reported]."),
    ("Did the crop fail?", "Yields [fell] [more] [steeply] [than] [in] [1976]."),
    ("Was the journey quick?", "It [took] [rather] [less] [time] [than] [advertised]."),
    ("Did the audience stay?", "More [remained] [than] [the] [organisers] [had] [expected]."),
  ]),

dict(
  hard=True,
  target="Locative inversion",
  why="When a place or time phrase opens the sentence, the verb can come before its subject: {ans}.",
  extras=["there", "it"],
  items=[
    ("What did the survey turn up?", "Among the findings [was] [a] [previously] [unrecorded] [species] [of] moss."),
    ("What was in the archive?", "In the box [were] [three] [letters] [never] [previously] [published]."),
    ("What stood on the hill?", "On the ridge [stood] [the] [remains] [of] [an] [older] fort."),
    ("What followed the talk?", "After the lecture [came] [a] [long] [and] [difficult] [discussion]."),
    ("What lay beneath?", "Beneath the floor [lay] [a] [layer] [of] [compacted] [ash]."),
    ("What was attached?", "To the report [were] [appended] [two] [pages] [of] [raw] data."),
    ("What came next?", "With the funding [came] [a] [set] [of] [strict] [conditions]."),
    ("What did they find inside?", "Inside the chamber [were] [found] [several] [fragments] [of] [painted] plaster."),
    ("What sits at the centre?", "At the heart [of] [the] [argument] [lies] [a] [single] assumption."),
    ("What followed the storm?", "In its wake [came] [weeks] [of] [unusually] [heavy] [flooding]."),
    ("What was on the table?", "On the desk [sat] [a] [pile] [of] [unopened] [envelopes]."),
    ("What did the vault hold?", "Within the vault [were] [stored] [the] [college's] [oldest] [charters]."),
    ("What lies to the north?", "To the north [rise] [the] [peaks] [of] [the] [older] range."),
    ("What accompanied the letter?", "With the letter [came] [a] [small] [package] [of] [photographs]."),
    ("What was in the report?", "Among the recommendations [was] [a] [call] [for] [wider] [consultation]."),
    ("What did the excavation reveal?", "Under the paving [lay] [the] [foundations] [of] [an] [earlier] hall."),
    ("What followed the announcement?", "After the statement [came] [a] [week] [of] [intense] [criticism]."),
    ("What hung on the wall?", "Above the fireplace [hung] [a] [portrait] [of] [the] [founder]."),
    ("What stood in the square?", "In the square [stood] [a] [monument] [to] [the] [town's] dead."),
    ("What did the file contain?", "Inside the folder [were] [copies] [of] [every] [rejected] [proposal]."),
  ]),

dict(
  hard=True,
  target="Agreement inside <i>one of the …</i>",
  why="In <i>one of the X that/who …</i> the relative clause describes the plural group, so its verb is plural: {ans}.",
  extras=["is", "was"],
  items=[
    ("Is she unusual?", "She is one of [the] [few] [students] [who] [have] [finished] early."),
    ("Is this common?", "It is one of [the] [many] [factors] [that] [make] [prediction] hard."),
    ("Did others do it?", "He is one of [only] [three] [people] [who] [have] [climbed] it."),
    ("Is the journal well known?", "It is one of [the] [few] [titles] [that] [remain] [in] print."),
    ("Is she experienced?", "She is one of [the] [candidates] [who] [have] [worked] [abroad]."),
    ("Is the species rare?", "It is one of [the] [birds] [that] [nest] [on] [cliffs]."),
    ("Did anyone else object?", "He was one of [the] [very] [few] [who] [raised] [objections]."),
    ("Is the building protected?", "It is one of [the] [structures] [that] [have] [listed] [status]."),
    ("Is she the only one?", "She is one of [the] [two] [researchers] [who] [have] [access]."),
    ("Is the method standard?", "It is one of [several] [approaches] [that] [produce] [similar] [results]."),
    ("Is he new here?", "He is one of [the] [staff] [who] [joined] [this] [autumn]."),
    ("Is the text unusual?", "It is one of [the] [manuscripts] [that] [survive] [in] [full]."),
    ("Are there others?", "This is one of [the] [samples] [that] [were] [never] [analysed]."),
    ("Is she qualified?", "She is one of [the] [few] [who] [hold] [both] [degrees]."),
    ("Is the route popular?", "It is one of [the] [paths] [that] [remain] [open] [in] winter."),
    ("Did many apply?", "He is one of [the] [applicants] [who] [were] [shortlisted] [twice]."),
    ("Is the rule unusual?", "It is one of [the] [clauses] [that] [have] [never] [been] used."),
    ("Is the college old?", "It is one of [the] [institutions] [that] [predate] [the] [charter]."),
    ("Is she on the committee?", "She is one of [the] [members] [who] [have] [served] [longest]."),
    ("Is the effect real?", "It is one of [the] [findings] [that] [have] [been] [replicated] widely."),
  ]),

dict(
  hard=True,
  target="Clause after a preposition",
  why="A preposition can take a whole clause as its object, introduced by <i>whether</i> or a question word but never by <i>that</i> or <i>if</i>: {ans}.",
  extras=["that", "if"],
  items=[
    ("Will the trip go ahead?", "Yes, regardless [of] [whether] [the] [weather] [improves] [or] not."),
    ("How long will it take?", "It varies depending [on] [how] [many] [samples] [we] [process]."),
    ("Is the fee fixed?", "It changes according [to] [where] [the] [applicant] [is] [based]."),
    ("Will she accept?", "That depends [on] [what] [the] [department] [can] [offer] her."),
    ("Is the rule absolute?", "It applies irrespective [of] [how] [long] [you] [have] [studied] here."),
    ("Can I choose the topic?", "Within limits, depending [on] [which] [supervisors] [are] [free] [this] term."),
    ("Is attendance required?", "Yes, regardless [of] [whether] [you] [have] [taken] [it] before."),
    ("How is the grade calculated?", "It depends [on] [how] [well] [the] [final] [essay] scores."),
    ("Will the price change?", "Possibly, according [to] [what] [the] [suppliers] [charge] [next] quarter."),
    ("Do I need the form?", "That depends [on] [whether] [you] [are] [applying] [from] abroad."),
    ("Is the deadline the same?", "It differs depending [on] [which] [route] [you] [are] [taking]."),
    ("Can we reschedule?", "Only depending [on] [when] [the] [room] [becomes] [free] again."),
    ("Is the result reliable?", "That turns [on] [how] [the] [sample] [was] [originally] selected."),
    ("Will they fund it?", "It hinges [on] [whether] [the] [pilot] [shows] [any] benefit."),
    ("Is the policy uniform?", "No, it varies [by] [how] [each] [faculty] [interprets] [the] guidance."),
    ("Should I apply now?", "That depends [on] [what] [you] [want] [from] [the] course."),
    ("Is the route fixed?", "It changes according [to] [where] [the] [ice] [has] [broken] up."),
    ("Do the rules differ?", "Slightly, depending [on] [whether] [the] [work] [is] [funded] externally."),
    ("Is the seminar assessed?", "That varies [with] [how] [the] [convenor] [designs] [the] term."),
    ("Can I keep the data?", "It depends [on] [what] [the] [consent] [form] [actually] says."),
  ]),
]
