# -*- coding: utf-8 -*-
"""Quantifiers, agreement, participial clauses, parallelism, adverbs, future, concession, purpose."""

PATTERNS = [
dict(
  target="Quantifiers with count and noncount nouns",
  why="Countable nouns take <i>few</i>, <i>many</i> and <i>number</i>; uncountable nouns take <i>little</i>, <i>much</i> and <i>amount</i>: {ans}.",
  items=[
    ("How is the turnout?", "There were [very] [few] [people] [at] the talk.", ["little"]),
    ("Did you have time?", "I had [very] [little] [time] [to] prepare.", ["few"]),
    ("Is there much interest?", "A [large] [number] [of] [students] signed up.", ["amount"]),
    ("How much data is there?", "We collected [a] [great] [deal] [of] information.", ["number"]),
    ("Are there many applicants?", "There aren't [as] [many] [as] [last] year.", ["much"]),
    ("Do you need help?", "I have [too] [much] [work] [this] week.", ["many"]),
    ("How many chairs are left?", "There are [only] [a] [few] [left].", ["little"]),
    ("Is there any milk?", "There's [hardly] [any] [milk] [left].", ["few"]),
    ("Did many attend?", "Only [a] [handful] [of] [people] came.", ["much"]),
    ("How much noise was there?", "There wasn't [much] [noise] [at] [all].", ["many"]),
    ("Are there enough copies?", "We have [fewer] [copies] [than] [we] need.", ["less"]),
    ("Is the traffic bad?", "There's [less] [traffic] [than] [usual].", ["fewer"]),
    ("How many errors did you find?", "I found [several] [small] [errors] [in] the text.", ["much"]),
    ("Do you get much sunlight?", "The room gets [plenty] [of] [natural] [light].", ["many"]),
    ("Are there many options?", "There are [a] [number] [of] [alternatives].", ["amount"]),
    ("How much did it cost?", "It took [a] [considerable] [amount] [of] money.", ["number"]),
    ("Did anyone object?", "In the end, [very] [few] [members] [objected].", ["little"]),
    ("Is there much evidence?", "There is [little] [direct] [evidence] [for] it.", ["few"]),
    ("How many drafts did you write?", "I wrote [quite] [a] [few] [drafts].", ["little"]),
    ("Do we have enough chairs?", "We need [a] [few] [more] [chairs].", ["little"]),
  ]),

dict(
  target="Subject-verb agreement",
  why="The verb agrees with the head of the subject, not with a noun that happens to sit next to it: {ans}.",
  items=[
    ("Were the results clear?", "The results of the experiment [were] [far] [more] [conclusive] than expected.", ["was"]),
    ("Is anyone waiting?", "There [are] [three] [people] [in] the queue.", ["is"]),
    ("Did everyone submit?", "Each of the students [has] [handed] [in] [a] draft.", ["have"]),
    ("Are the books here?", "One of the volumes [is] [still] [missing] [from] the shelf.", ["are"]),
    ("Is the committee meeting?", "The committee [meets] [on] [the] [first] Monday.", ["meet"]),
    ("Are there any updates?", "There [is] [one] [change] [to] the schedule.", ["are"]),
    ("Did the data support it?", "Neither of the samples [shows] [any] [sign] [of] contamination.", ["show"]),
    ("Is the equipment ready?", "All of the equipment [has] [been] [tested] [already].", ["have"]),
    ("Are the students prepared?", "Every one of them [knows] [the] [material] [well].", ["know"]),
    ("Is the news good?", "The news [was] [better] [than] [we] feared.", ["were"]),
    ("Are the statistics reliable?", "The statistics in this chapter [seem] [unusually] [precise] [to] me.", ["seems"]),
    ("Did anyone notice?", "Nobody in the seminars [was] [paying] [close] [attention].", ["were"]),
    ("Are the rooms booked?", "A number of rooms [have] [already] [been] [reserved].", ["has"]),
    ("Is the research finished?", "The research on both sites [is] [nearly] [complete] [now].", ["are"]),
    ("Are the twins here?", "Neither twin [has] [arrived] [on] [time].", ["have"]),
    ("Is there enough furniture?", "There [are] [not] [enough] [desks] upstairs.", ["is"]),
    ("Did the group agree?", "The majority of members [were] [in] [favor] [of] the change.", ["was"]),
    ("Is physics difficult?", "Physics [is] [the] [hardest] [subject] I take.", ["are"]),
    ("Are the criteria clear?", "The criteria for selection [are] [published] [on] [the] website.", ["is"]),
    ("Did everything arrive?", "Each of the packages [was] [delivered] [on] [time].", ["were"]),
  ]),

dict(
  target="Participial adverbial clause",
  why="<i>Having</i> plus a past participle compresses a completed earlier action into a clause with no subject of its own: {ans}.",
  extras=["because"],
  items=[
    ("Why did you leave early?", "I went home, [having] [finished] [the] [experiment] early."),
    ("How did she know the answer?", "She answered quickly, [having] [read] [the] [chapter] twice."),
    ("Why was he calm?", "He stayed calm, [having] [rehearsed] [the] [talk] all week."),
    ("Why did they cancel?", "They cancelled the trip, [having] [checked] [the] [forecast] first."),
    ("How did you finish so fast?", "I finished early, [having] [started] [the] [night] before."),
    ("Why did she decline?", "She declined the offer, [having] [accepted] [another] [one] already."),
    ("Why were you confident?", "I felt ready, [having] [practiced] [the] [routine] daily."),
    ("How did he spot the error?", "He noticed it at once, [having] [seen] [the] [same] mistake before."),
    ("Why did they delay?", "They waited a week, [having] [received] [no] [reply]."),
    ("Why is the room empty?", "Everyone left, [having] [heard] [the] [announcement]."),
    ("How did you get the job?", "I was hired quickly, [having] [worked] [there] [before]."),
    ("Why did she rewrite it?", "She revised the draft, [having] [reread] [the] [feedback] carefully."),
    ("Why were you late?", "I arrived late, [having] [missed] [the] [first] bus."),
    ("How did they prepare?", "They packed lightly, [having] [travelled] [that] [route] before."),
    ("Why did he refuse?", "He turned it down, [having] [promised] [the] [slot] to someone else."),
    ("Why is the lab closed?", "It shut early, [having] [completed] [the] [week's] runs."),
    ("How did you know the way?", "I walked straight there, [having] [studied] [the] [map] beforehand."),
    ("Why did she apply again?", "She reapplied this year, [having] [strengthened] [her] [portfolio]."),
    ("Why was the talk short?", "He finished early, [having] [covered] [every] [point] quickly."),
    ("How did they win?", "They won comfortably, [having] [trained] [all] [summer]."),
  ]),

dict(
  target="Correlative conjunctions",
  why="Correlative pairs such as <i>not only … but also</i>, <i>both … and</i> and <i>either … or</i> must join two grammatically parallel elements: {ans}.",
  items=[
    ("What is the policy meant to do?", "It is intended [not] [only] [to] [reduce] emissions but also to lower costs.", ["as"]),
    ("Which option did they choose?", "They decided [either] [to] [postpone] [it] or to cancel.", ["both"]),
    ("What did the study show?", "It examined [both] [the] [causes] [and] the effects.", ["either"]),
    ("Is she a writer or a teacher?", "She is [both] [a] [novelist] [and] a lecturer.", ["either"]),
    ("How do they fund it?", "Support comes [not] [only] [from] [alumni] but also from grants.", ["also"]),
    ("What are the requirements?", "You must [either] [submit] [a] [portfolio] or sit the exam.", ["neither"]),
    ("Did anyone agree?", "In the end, [neither] [the] [chair] [nor] the treasurer agreed.", ["either"]),
    ("What does the course cover?", "It teaches [both] [theory] [and] [practice] equally.", ["either"]),
    ("Why did you choose it?", "The program is [not] [only] [affordable] [but] also flexible.", ["also"]),
    ("How will you travel?", "I will go [either] [by] [train] [or] by coach.", ["both"]),
    ("What impressed the panel?", "They praised [both] [her] [research] [and] her teaching.", ["either"]),
    ("Is the role technical?", "It requires [not] [only] [coding] [but] also writing.", ["as"]),
    ("Did they publish it?", "The paper appeared [neither] [in] [print] [nor] online.", ["either"]),
    ("What should I bring?", "Bring [either] [your] [laptop] [or] a notebook.", ["both"]),
    ("Why is the site important?", "It is valued [both] [for] [its] [age] and for its size.", ["either"]),
    ("What did the review say?", "It found the design [not] [only] [elegant] [but] also practical.", ["also"]),
    ("How is the grant judged?", "Panels weigh [both] [originality] [and] [feasibility].", ["either"]),
    ("Can I pay later?", "You may pay [either] [now] [or] [at] registration.", ["both"]),
    ("What does the job involve?", "It involves [not] [only] [fieldwork] [but] also analysis.", ["as"]),
    ("Were they satisfied?", "The result pleased [neither] [the] [students] [nor] the staff.", ["either"]),
  ]),

dict(
  target="Frequency adverb placement",
  why="A frequency adverb goes before a main verb, but after <i>be</i> and after the first auxiliary: {ans}.",
  extras=["ever"],
  items=[
    ("Do you go to the gym?", "I [usually] [go] [before] [breakfast]."),
    ("Is she late often?", "She is [hardly] [ever] [late] [for] seminars.", ["always"]),
    ("Do they meet weekly?", "They [have] [always] [met] [on] Fridays."),
    ("Do you drink coffee?", "I [rarely] [drink] [it] [after] noon."),
    ("Is the office open Saturdays?", "It is [never] [open] [at] [the] weekend."),
    ("Do you check email at night?", "I [sometimes] [check] [it] [before] bed."),
    ("Has he missed a class?", "He [has] [never] [missed] [a] single session."),
    ("Do you take notes?", "I [always] [take] [notes] [by] hand."),
    ("Is the bus punctual?", "It is [seldom] [on] [time] [in] winter."),
    ("Do they update the site?", "They [occasionally] [update] [it] [on] Mondays."),
    ("Have you been there?", "I [have] [often] [walked] [past] it."),
    ("Do you work weekends?", "I [normally] [work] [only] [on] weekdays."),
    ("Is he usually this quiet?", "He is [generally] [quite] [talkative] [in] class."),
    ("Do you eat in the hall?", "I [hardly] [ever] [eat] [there] now.", ["always"]),
    ("Has the policy changed?", "It [has] [rarely] [been] [revised] since then."),
    ("Do you cycle to campus?", "I [frequently] [cycle] [when] [it's] dry."),
    ("Is the lab crowded?", "It is [almost] [always] [full] [by] ten."),
    ("Do they publish quickly?", "They [usually] [publish] [within] [six] months."),
    ("Have you tried it?", "I [have] [never] [tried] [that] method."),
    ("Do you read the news?", "I [regularly] [read] [it] [on] the train."),
  ]),

dict(
  target="Future perfect and future continuous",
  why="<i>Will have</i> plus a past participle looks back from a future point; <i>will be</i> plus an <i>-ing</i> form describes something in progress then: {ans}.",
  extras=["is"],
  items=[
    ("Will the project be done by June?", "We [will] [have] [finished] [the] analysis by then."),
    ("What are you doing at noon?", "I [will] [be] [sitting] [the] exam then."),
    ("Will she have graduated?", "She [will] [have] [completed] [her] degree by spring."),
    ("Where will you be tomorrow?", "I [will] [be] [working] [in] the archive."),
    ("How long will it take?", "By Friday we [will] [have] [run] [every] test."),
    ("Will they still be here?", "They [will] [be] [waiting] [at] the entrance."),
    ("Will the book be out?", "It [will] [have] [been] [published] by autumn."),
    ("What about next week?", "I [will] [be] [travelling] [for] three days."),
    ("Will you have read it?", "I [will] [have] [finished] [it] before class."),
    ("Will the work continue?", "The crew [will] [be] [drilling] [until] March."),
    ("Will the funding run out?", "It [will] [have] [ended] [by] next term."),
    ("What will you be doing then?", "I [will] [be] [presenting] [in] the main hall."),
    ("Will they have moved?", "They [will] [have] [relocated] [the] office by then."),
    ("Will the shop be open?", "It [will] [be] [closing] [as] we arrive."),
    ("Will you finish in time?", "I [will] [have] [submitted] [everything] by Thursday."),
    ("Where will the team be?", "They [will] [be] [training] [at] the north field."),
    ("Will the data be ready?", "We [will] [have] [processed] [it] all by Monday."),
    ("What happens at three?", "The panel [will] [be] [interviewing] [candidates] then."),
    ("Will she have heard?", "She [will] [have] [received] [the] letter by now."),
    ("Will it still be raining?", "It [will] [be] [pouring] [by] the time we leave."),
  ]),

dict(
  target="Concessive clause",
  why="<i>Although</i> and <i>even though</i> introduce a clause, while <i>despite</i> and <i>in spite of</i> introduce a noun phrase or gerund: {ans}.",
  extras=["but"],
  items=[
    ("Was the vaccine effective?", "It worked well, [although] [distribution] [remained] [a] problem."),
    ("Did the plan succeed?", "It succeeded, [even] [though] [the] [budget] was cut."),
    ("Is the flat good?", "I like it, [although] [the] [kitchen] [is] small."),
    ("Was the trip worthwhile?", "It was, [despite] [the] [poor] [weather]."),
    ("Did she enjoy the course?", "She did, [even] [though] [it] [was] demanding."),
    ("Is the evidence strong?", "It is persuasive, [although] [the] [sample] [is] small."),
    ("Did they finish on time?", "They did, [in] [spite] [of] [the] delays."),
    ("Was the talk clear?", "It was, [although] [the] [topic] [was] technical."),
    ("Do you recommend it?", "I do, [even] [though] [the] [price] is high."),
    ("Did the team play well?", "They played well, [despite] [losing] [two] [players]."),
    ("Is the software useful?", "It helps, [although] [it] [crashes] [occasionally]."),
    ("Was the museum busy?", "It was quiet, [even] [though] [entry] [was] free."),
    ("Did he pass?", "He passed, [although] [he] [missed] [several] classes."),
    ("Is the job secure?", "It seems stable, [despite] [the] [recent] [cuts]."),
    ("Did you like the ending?", "I did, [even] [though] [it] [felt] rushed."),
    ("Was the hike hard?", "It was manageable, [although] [the] [last] [hour] hurt."),
    ("Is the data usable?", "It is, [in] [spite] [of] [some] gaps."),
    ("Did they accept the offer?", "They accepted, [although] [the] [terms] [were] poor."),
    ("Was the room comfortable?", "It was fine, [even] [though] [it] [faced] the road."),
    ("Did the repair work?", "It held, [despite] [the] [heavy] [use]."),
  ]),

dict(
  target="Purpose clause",
  why="Purpose is expressed by <i>so that</i> plus a clause or <i>in order to</i> plus a base verb: {ans}.",
  extras=["for"],
  items=[
    ("Why did you email her?", "I wrote [so] [that] [she] [would] have time to reply."),
    ("Why the early start?", "We left early [in] [order] [to] [avoid] the traffic."),
    ("Why did you record it?", "I recorded it [so] [that] [I] [could] review it later."),
    ("Why take the slower route?", "I go that way [in] [order] [to] [see] the river."),
    ("Why label the samples?", "We label them [so] [that] [nothing] [gets] mixed up."),
    ("Why did you print two?", "I printed spares [in] [order] [to] [have] a backup."),
    ("Why the extra practice?", "She practices daily [so] [that] [her] [timing] improves."),
    ("Why call ahead?", "Call first [so] [that] [they] [can] prepare the room."),
    ("Why did they lower the price?", "They cut it [in] [order] [to] [attract] more students."),
    ("Why write it down?", "Note it [so] [that] [you] [don't] forget."),
    ("Why the second reading?", "I reread it [in] [order] [to] [catch] the errors."),
    ("Why arrive at eight?", "Come early [so] [that] [we] [can] set up."),
    ("Why did you keep the draft?", "I saved it [in] [order] [to] [compare] versions."),
    ("Why the shorter slides?", "I trimmed them [so] [that] [the] [talk] fits."),
    ("Why book in advance?", "Book now [in] [order] [to] [secure] a place."),
    ("Why did she stay late?", "She stayed [so] [that] [the] [team] could finish."),
    ("Why the second sensor?", "We added one [in] [order] [to] [check] the readings."),
    ("Why email the group?", "I messaged everyone [so] [that] [nobody] [misses] it."),
    ("Why leave a margin?", "Leave space [in] [order] [to] [add] comments."),
    ("Why the rehearsal?", "We rehearse [so] [that] [the] [timing] feels natural."),
  ]),
]
