# -*- coding: utf-8 -*-
"""HARD tier: pied-piping, concessive inversion, absolutes, not-only inversion, extraposition."""

PATTERNS = [
dict(
  hard=True,
  target="Preposition before <i>whom</i> or <i>which</i>",
  why="In formal English the preposition moves to the front of the relative clause and takes <i>whom</i> or <i>which</i>, never <i>who</i> or <i>that</i>: {ans}.",
  extras=["who", "that"],
  items=[
    ("Which colleague do you mean?", "I mean the researcher [with] [whom] [I] [have] [shared] [an] office."),
    ("Which journal published it?", "It appeared in a journal [to] [which] [our] [library] [no] [longer] subscribes."),
    ("Which committee decided?", "It was the panel [on] [which] [she] [served] [last] [year]."),
    ("Which supervisor signed it?", "The professor [under] [whom] [I] [worked] [last] [year] signed it."),
    ("Which building was it?", "The hall [in] [which] [the] [lecture] [was] [held] has closed."),
    ("Which grant paid for it?", "The fund [from] [which] [we] [drew] [the] [money] has ended."),
    ("Which student did you mention?", "The candidate [about] [whom] [we] [spoke] [last] [week] withdrew."),
    ("Which method did you use?", "The technique [by] [which] [the] [samples] [were] [dated] is standard."),
    ("Which archive holds it?", "The collection [to] [which] [the] [letters] [belong] [is] private."),
    ("Which colleagues attended?", "The delegates [among] [whom] [she] [sat] [were] [all] economists."),
    ("Which chapter covers it?", "The section [in] [which] [he] [outlines] [the] [model] is short."),
    ("Which laboratory tested it?", "The facility [at] [which] [the] [work] [was] [done] has moved."),
    ("Which mentor helped most?", "The tutor [without] [whom] [I] [would] [have] [failed] retired."),
    ("Which river was surveyed?", "The valley [through] [which] [the] [river] [runs] [is] protected."),
    ("Which author do you cite?", "The historian [upon] [whom] [the] [argument] [rests] [is] contested."),
    ("Which period does it cover?", "The decade [during] [which] [the] [trade] [collapsed] [is] documented."),
    ("Which conference was it?", "The meeting [at] [which] [they] [first] [presented] [was] small."),
    ("Which colleagues signed?", "The staff [for] [whom] [the] [policy] [was] [written] objected."),
    ("Which sources survive?", "The records [of] [which] [only] [fragments] [remain] [are] medieval."),
    ("Which bridge collapsed?", "The crossing [over] [which] [the] [lorries] [passed] [was] old."),
  ]),

dict(
  hard=True,
  target="Concessive inversion",
  why="A fronted adjective followed by <i>though</i> or <i>as</i> concedes a point, inverting the usual order: {ans}.",
  extras=["although", "however"],
  items=[
    ("Was the climb hard?", "Yes; [hard] [though] [the] [climb] [was], we reached the summit."),
    ("Did you manage to persuade her?", "No; [much] [as] [I] [wanted] [to], I could not persuade her."),
    ("Was the evidence convincing?", "Somewhat; [strong] [though] [the] [data] [were], doubts remained."),
    ("Did the delay matter?", "A little; [late] [as] [the] [parts] [arrived], we still finished."),
    ("Is the method popular?", "Rarely; [elegant] [though] [the] [method] [is], few laboratories use it."),
    ("Did she enjoy the course?", "Mostly; [demanding] [as] [the] [course] [was], she learned a lot."),
    ("Was the room adequate?", "Barely; [small] [though] [the] [space] [was], everyone fitted."),
    ("Did the argument persuade you?", "Partly; [clever] [as] [the] [reasoning] [was], I disagreed."),
    ("Was the journey worth it?", "Certainly; [long] [though] [the] [drive] [was], the site amazed us."),
    ("Did he finish the race?", "He did; [exhausted] [though] [he] [clearly] [was], he finished."),
    ("Was the funding enough?", "Hardly; [generous] [though] [the] [grant] [seemed], costs rose."),
    ("Did the plan convince the board?", "Eventually; [risky] [as] [the] [proposal] [looked], they approved it."),
    ("Is the software reliable?", "Mostly; [old] [though] [the] [system] [is], it rarely fails."),
    ("Did the team improve?", "Slowly; [talented] [as] [the] [players] [were], results came late."),
    ("Was the lecture clear?", "Broadly; [technical] [though] [the] [subject] [was], he explained it well."),
    ("Did you finish the novel?", "Eventually; [dense] [as] [the] [prose] [was], I persevered."),
    ("Was the museum worth visiting?", "Very; [crowded] [though] [the] [galleries] [were], the collection impressed."),
    ("Did the repair hold?", "So far; [temporary] [as] [the] [fix] [is], nothing has leaked."),
    ("Was the summer productive?", "Fairly; [short] [though] [the] [season] [was], we gathered enough."),
    ("Did she accept the criticism?", "Gracefully; [harsh] [as] [the] [review] [was], she thanked them."),
  ]),

dict(
  hard=True,
  target="Absolute participial construction",
  why="An absolute clause keeps its own subject and attaches a participle to it, with no conjunction: {ans}.",
  extras=["because", "and"],
  items=[
    ("When did the analysis start?", "The data [having] [been] [collected] [over] [winter], we began analysis."),
    ("Why did the meeting end early?", "The agenda [having] [been] [exhausted], [the] [chair] [closed] it."),
    ("When can we publish?", "The results [having] [been] [verified] [by] [two] [reviewers], publication can proceed."),
    ("Why is the site quiet?", "The permits [having] [been] [withdrawn] [last] [month], work has stopped."),
    ("When did they leave?", "The storm [having] [passed] [by] [early] [morning], the crew departed."),
    ("Why was the room rearranged?", "The seating [having] [proved] [inadequate] [once] [before], staff rebuilt it."),
    ("When did the price fall?", "Demand [having] [dropped] [through] [the] [winter], prices fell sharply."),
    ("Why did she take the role?", "Her thesis [having] [been] [accepted] [that] [spring], she was free."),
    ("When will the road reopen?", "The repairs [having] [been] [completed] [ahead] [of] schedule, it opens tomorrow."),
    ("Why did they change suppliers?", "The contract [having] [expired] [in] [the] [autumn], they looked elsewhere."),
    ("When did the term end?", "The examinations [having] [finished] [at] [the] [weekend], the campus emptied."),
    ("Why is the lab empty?", "The grant [having] [run] [out] [last] [spring], the team dispersed."),
    ("When did you start writing?", "The fieldwork [having] [ended] [in] [late] [summer], I began drafting."),
    ("Why did the case close?", "The witness [having] [withdrawn] [her] [written] [statement], the case collapsed."),
    ("When did the price stabilise?", "Supply [having] [recovered] [over] [the] [spring], costs levelled off."),
    ("Why was the talk moved?", "The hall [having] [been] [double] [booked] [again], they used the annexe."),
    ("When did the work resume?", "The inspection [having] [been] [passed] [without] [comment], building continued."),
    ("Why did she decline?", "Another offer [having] [arrived] [the] [same] [week], she chose it."),
    ("When did the river subside?", "The rain [having] [stopped] [two] [days] [earlier], the level dropped."),
    ("Why is the archive closed?", "The catalogue [having] [been] [lost] [in] [transit], access is suspended."),
  ]),

dict(
  hard=True,
  target="Inversion after fronted <i>not only</i>",
  why="<i>Not only</i> at the front of a clause forces the auxiliary in front of the subject, and the second clause carries <i>but</i>: {ans}.",
  extras=["and", "too"],
  items=[
    ("Did she just finish the draft?", "Not only [did] [she] [finish] [it], [but] [she] also revised twice."),
    ("Was the talk just informative?", "Not only [was] [it] [informative], [but] [it] [was] entertaining."),
    ("Did the grant cover travel?", "Not only [did] [it] [cover] [travel], [but] [it] funded equipment."),
    ("Was he late again?", "Not only [was] [he] [late], [but] [he] [forgot] the slides."),
    ("Did they publish the data?", "Not only [did] [they] [publish] [it], [but] [they] released the code."),
    ("Was the winter cold?", "Not only [was] [it] [cold], [but] [it] [lasted] until April."),
    ("Did she pass the exam?", "Not only [did] [she] [pass], [but] [she] [topped] the year."),
    ("Was the museum free?", "Not only [was] [entry] [free], [but] [the] [tour] was too."),
    ("Did the repair work?", "Not only [did] [it] [hold], [but] [it] [cost] almost nothing."),
    ("Was the room booked?", "Not only [was] [it] [booked], [but] [it] [was] booked twice."),
    ("Did he apologise?", "Not only [did] [he] [apologise], [but] [he] [rewrote] the section."),
    ("Was the paper rejected?", "Not only [was] [it] [rejected], [but] [the] [reviewers] were harsh."),
    ("Did the storm damage the roof?", "Not only [did] [it] [damage] [the] [roof], but it flooded the cellar."),
    ("Was the course useful?", "Not only [was] [it] [useful], [but] [it] [changed] my plans."),
    ("Did they finish on time?", "Not only [did] [they] [finish], [but] [they] [finished] early."),
    ("Was the evidence weak?", "Not only [was] [it] [weak], [but] [it] [contradicted] the abstract."),
    ("Did she learn the language?", "Not only [did] [she] [learn] [it], [but] [she] teaches it now."),
    ("Was the trip expensive?", "Not only [was] [it] [expensive], [but] [it] [was] exhausting."),
    ("Did the software crash?", "Not only [did] [it] [crash], [but] [it] [lost] the file."),
    ("Was the audience small?", "Not only [was] [it] [small], [but] [half] [of] them left."),
  ]),

dict(
  hard=True,
  target="Extraposed subject clause",
  why="<i>It</i> stands in for a clause that has been moved to the end of the sentence: {ans}.",
  extras=["what", "this"],
  items=[
    ("Is the theory settled?", "It [is] [now] [widely] [accepted] [that] [the] climate is warming."),
    ("Were people shocked?", "It [came] [as] [no] [surprise] [that] [she] resigned."),
    ("Is the timing important?", "It [matters] [a] [great] [deal] [that] [we] file early."),
    ("Did anyone expect this?", "It [had] [long] [been] [suspected] [that] [the] data were flawed."),
    ("Is the rule clear?", "It [remains] [unclear] [to] [everyone] [whether] [attendance] is required."),
    ("Was the outcome obvious?", "It [was] [apparent] [from] [the] [start] [that] nobody agreed."),
    ("Does the order matter?", "It [makes] [little] [difference] [whether] [you] [file] first."),
    ("Is the claim defensible?", "It [seems] [unlikely] [to] [most] [readers] [that] he verified it."),
    ("Were they surprised?", "It [struck] [the] [committee] [as] [odd] [that] nobody objected."),
    ("Is the funding certain?", "It [has] [yet] [to] [be] [decided] [whether] the grant continues."),
    ("Did the delay cause problems?", "It [turned] [out] [in] [the] [end] [that] nothing was lost."),
    ("Is her account reliable?", "It [is] [generally] [agreed] [among] [historians] [that] she exaggerated."),
    ("Does the method scale?", "It [is] [far] [from] [obvious] [that] [it] scales."),
    ("Was the decision popular?", "It [surprised] [nobody] [in] [the] [department] [that] staff complained."),
    ("Is the deadline firm?", "It [appears] [from] [the] [notice] [that] [extensions] are possible."),
    ("Did the study settle it?", "It [remains] [an] [open] [question] [whether] [the] effect is real."),
    ("Was the cost justified?", "It [is] [hard] [to] [argue] [that] [the] expense was necessary."),
    ("Did they know in advance?", "It [became] [clear] [only] [afterwards] [that] [she] had resigned."),
    ("Is the result reproducible?", "It [has] [never] [been] [shown] [that] [others] can repeat it."),
    ("Was the reaction expected?", "It [was] [something] [of] [a] [shock] [that] attendance halved."),
  ]),
]
