# -*- coding: utf-8 -*-
"""Comparison, phrasal verbs, inversion, degree and result clauses."""

PATTERNS = [
dict(
  target="Comparative with <i>than</i>",
  why="A comparative form is completed by <i>than</i>, never by <i>as</i>: {ans}.",
  extras=["as"],
  items=[
    ("How was the second exam?", "It was [much] [harder] [than] [the] first one."),
    ("Is the new library better?", "It's [far] [quieter] [than] [the] old reading room."),
    ("How does the commute compare?", "It's [considerably] [longer] [than] [it] was last year."),
    ("Which lab section should I take?", "The morning one is [less] [crowded] [than] [the] afternoon."),
    ("Is the textbook expensive?", "It's [cheaper] [online] [than] [at] the campus store."),
    ("How is the new coach?", "She's [more] [demanding] [than] [the] previous one."),
    ("Did the second draft improve?", "It's [significantly] [clearer] [than] [the] first attempt."),
    ("Is this route faster?", "It's [slightly] [shorter] [than] [the] main road."),
    ("How was the turnout?", "It was [smaller] [than] [anyone] [had] expected."),
    ("Which dorm is better?", "The north building is [warmer] [than] [the] [south] one."),
    ("Is the seminar hard?", "It's [more] [demanding] [than] [I] anticipated."),
    ("How does this year compare?", "Enrollment is [higher] [than] [it] [has] been in a decade."),
    ("Is the film worth seeing?", "The book is [far] [more] [interesting] [than] the film."),
    ("How is the new software?", "It's [noticeably] [slower] [than] [the] old version."),
    ("Which professor grades harder?", "Dr. Ellis is [stricter] [than] [most] [of] the department."),
    ("Is the gym busy in the morning?", "It's [busier] [at] [six] [than] at noon."),
    ("How was the weather?", "It was [colder] [than] [we] [had] packed for."),
    ("Is the seminar useful?", "It's [more] [practical] [than] [the] lecture course."),
    ("Which apartment did you pick?", "I took the one [closer] [to] [campus] [than] the others."),
    ("How is the second edition?", "It's [better] [organized] [than] [the] original."),
  ]),

dict(
  target="Equal comparison with <i>as … as</i>",
  why="An equal comparison brackets the adjective or adverb between two instances of <i>as</i>: {ans}.",
  extras=["more"],
  items=[
    ("How does this course compare with last term's?", "It [isn't] [nearly] [as] [demanding] [as] that one was."),
    ("Is the new hall bigger?", "It's [about] [as] [large] [as] [the] old one."),
    ("Was the trip expensive?", "It wasn't [as] [costly] [as] [I] feared."),
    ("Is she a strong candidate?", "She's [just] [as] [qualified] [as] anyone else."),
    ("How was the second lecture?", "It wasn't [quite] [as] [clear] [as] the first."),
    ("Is the walk far?", "It's [not] [as] [far] [as] it looks."),
    ("How did the team do?", "They played [as] [well] [as] [they] ever have."),
    ("Is the exam long?", "It's [twice] [as] [long] [as] [the] midterm."),
    ("Was the talk technical?", "It wasn't [as] [technical] [as] [the] abstract suggested."),
    ("How is the new roommate?", "He's [nearly] [as] [tidy] [as] you are."),
    ("Is the coffee good there?", "It's [not] [quite] [as] [strong] as I like."),
    ("Did the storm cause damage?", "It wasn't [as] [severe] [as] [the] forecast warned."),
    ("How does the salary compare?", "It's [roughly] [as] [high] [as] [the] other offer."),
    ("Is the seminar full?", "It's [almost] [as] [popular] [as] [the] workshop."),
    ("Was the paper difficult?", "It wasn't [as] [hard] [as] [it] looked."),
    ("How is her Spanish?", "She speaks [as] [fluently] [as] [a] native."),
    ("Is the older model fine?", "It works [just] [as] [reliably] [as] the new one."),
    ("Did the second run improve?", "It was [exactly] [as] [fast] [as] before."),
    ("Is the north route better?", "It's [not] [as] [scenic] [as] [the] coastal road."),
    ("How was the audience?", "It wasn't [as] [large] [as] [last] year's."),
  ]),

dict(
  target="Superlative",
  why="A superlative takes <i>the</i> and compares one thing against a whole group: {ans}.",
  extras=["more"],
  items=[
    ("Which lecture did you like best?", "The one on glaciers was [the] [most] [engaging] [of] the series."),
    ("Which route is quickest?", "The river path is [the] [fastest] [way] [to] campus."),
    ("Who did best on the exam?", "She had [the] [highest] [score] [in] the section."),
    ("Which library is quietest?", "The law library is [the] [quietest] [place] [on] campus."),
    ("Which day is busiest?", "Monday is [the] [busiest] [day] [of] the week."),
    ("Which dorm is oldest?", "Kent Hall is [the] [oldest] [building] [on] the quad."),
    ("What was the best part?", "The fieldwork was [by] [far] [the] [most] rewarding part."),
    ("Which chapter is hardest?", "Chapter nine is [the] [most] [difficult] [one] to follow."),
    ("Which option is cheapest?", "The bus is [the] [least] [expensive] [way] to travel."),
    ("Who has the most experience?", "Our supervisor is [the] [most] [experienced] [person] here."),
    ("Which season is best there?", "Autumn is [the] [most] [pleasant] [time] to visit."),
    ("Which essay was strongest?", "The third one was [the] [best] [argued] [of] the three."),
    ("Which lab is largest?", "The imaging suite is [the] [biggest] [facility] [in] the building."),
    ("Which class filled first?", "The seminar was [the] [first] [course] [to] close."),
    ("What is the main obstacle?", "Funding is [the] [greatest] [challenge] [we] face."),
    ("Which draft should I keep?", "Keep the one with [the] [clearest] [structure] [of] them all."),
    ("Who arrived earliest?", "The volunteers were [the] [first] [people] [to] arrive."),
    ("Which result surprised you most?", "The control group gave [the] [strangest] [data] [of] all."),
    ("Which month is wettest?", "June is [the] [rainiest] [month] [of] the year."),
    ("Which talk ran longest?", "The closing lecture was [the] [longest] [session] [of] the day."),
  ]),

dict(
  target="Double comparative",
  why="The <i>the … the …</i> pattern puts the comparative phrase first in each half and follows each with a clause: {ans}.",
  extras=["very"],
  items=[
    ("Do the two species look related?", "The [more] [closely] they [are] [compared], the [clearer] the link becomes."),
    ("Does practice help?", "The [more] [you] [rehearse], the [less] [nervous] you feel."),
    ("Is the reading getting easier?", "The [further] [I] [read], the [more] [sense] it makes."),
    ("Should we start early?", "The [earlier] [we] [begin], the [better] our chances are."),
    ("Does the data improve?", "The [larger] [the] [sample], the [smaller] the error."),
    ("Is the hill steep?", "The [higher] [you] [climb], the [thinner] [the] air gets."),
    ("Does the course get harder?", "The [deeper] [we] [go], the [more] [technical] it becomes."),
    ("Should I write more drafts?", "The [more] [you] [revise], the [stronger] the argument."),
    ("Is the commute worse now?", "The [later] [I] [leave], the [heavier] the traffic."),
    ("Does the medication help?", "The [longer] [she] [takes] [it], the [better] she sleeps."),
    ("Are the seats better up front?", "The [closer] [you] [sit], the [louder] it seems."),
    ("Is the city quieter at night?", "The [later] [it] [gets], the [calmer] the streets are."),
    ("Does the recipe need time?", "The [slower] [you] [cook] [it], the [richer] the flavor."),
    ("Is the group getting bigger?", "The [more] [people] [join], the [harder] scheduling becomes."),
    ("Should I read the footnotes?", "The [more] [carefully] [you] [read], the [more] you notice."),
    ("Is the lens better?", "The [wider] [the] [aperture], the [blurrier] the background."),
    ("Does repetition help memory?", "The [more] [often] [you] [test] yourself, the [longer] you remember."),
    ("Is the market changing?", "The [faster] [prices] [rise], the [fewer] buyers appear."),
    ("Should we simplify the slides?", "The [fewer] [words] [you] [use], the [clearer] the point."),
    ("Is the trail harder in winter?", "The [colder] [it] [gets], the [slipperier] the rocks are."),
  ]),

dict(
  target="Separable phrasal verb with a pronoun object",
  why="When the object of a separable phrasal verb is a pronoun it must come between the verb and the particle: {ans}.",
  items=[
    ("I found your notes on the kitchen table.", "Oh, could you [drop] [them] [off] [at] the front desk?", ["to"]),
    ("Your library books are due.", "I'll [take] [them] [back] [this] afternoon.", ["again"]),
    ("The heater is still on.", "Could you [turn] [it] [off] [before] you leave?", ["out"]),
    ("Here are the forms you wanted.", "Thanks, I'll [fill] [them] [in] [tonight].", ["on"]),
    ("The music is too quiet.", "I'll [turn] [it] [up] [a] little.", ["on"]),
    ("These boxes are blocking the door.", "I'll [move] [them] [out] [of] the way.", ["off"]),
    ("You left your jacket here.", "I'll [pick] [it] [up] [tomorrow] morning.", ["on"]),
    ("The draft has three typos.", "Point [them] [out] [and] [I'll] fix them.", ["up"]),
    ("Someone has to cancel the booking.", "I'll [call] [it] [off] [this] evening.", ["out"]),
    ("The lamp isn't working.", "Try [plugging] [it] [in] [again].", ["on"]),
    ("These files are duplicates.", "Just [throw] [them] [away] [when] you can.", ["off"]),
    ("The proposal needs shortening.", "I'll [cut] [it] [down] [by] a page.", ["off"]),
    ("Your sister called twice.", "I'll [ring] [her] [back] [after] dinner.", ["again"]),
    ("The chairs are still stacked.", "Help me [set] [them] [up] [before] six.", ["on"]),
    ("This word keeps appearing.", "Look [it] [up] [in] [the] glossary.", ["on"]),
    ("The application is half finished.", "I'll [hand] [it] [in] [on] Friday.", ["over"]),
    ("The printer jammed again.", "Let me [sort] [it] [out] [right] now.", ["off"]),
    ("You borrowed my charger.", "I'll [give] [it] [back] [tomorrow].", ["again"]),
    ("The poster is crooked.", "I'll [put] [it] [up] [again] properly.", ["on"]),
    ("These names are wrong.", "Cross [them] [out] [and] [rewrite] the list.", ["off"]),
  ]),

dict(
  target="Inversion after a negative adverbial",
  why="When a negative or limiting adverbial opens a sentence, the subject and auxiliary invert: {ans}.",
  extras=["was"],
  items=[
    ("Has a documentary ever caused this much argument?", "Rarely [has] [a] [single] [film] [generated] such debate."),
    ("Did you expect the result?", "Never [have] [I] [seen] [data] [scatter] like that."),
    ("Was the change announced?", "Not once [did] [the] [department] [mention] it."),
    ("Did she hesitate?", "At no point [did] [she] [question] [the] method."),
    ("Is the office ever this quiet?", "Seldom [is] [the] [building] [this] empty."),
    ("Did they warn anyone?", "Under no circumstances [should] [you] [enter] [without] a badge."),
    ("Was the talk well attended?", "Rarely [do] [so] [many] [people] show up."),
    ("Did he pass easily?", "Only after [three] [attempts] [did] [he] pass."),
    ("Has the policy ever changed?", "Never [before] [had] [the] [rules] been revised."),
    ("Did you notice the error?", "Not until [the] [second] [reading] [did] I notice."),
    ("Do they often cancel?", "Seldom [does] [the] [department] [cancel] a seminar."),
    ("Was anyone prepared?", "Hardly [had] [we] [sat] [down] when it began."),
    ("Did she complain?", "At no time [did] [she] [raise] [an] objection."),
    ("Is the lab ever free?", "Rarely [is] [there] [an] [open] bench."),
    ("Did the team expect to win?", "Little [did] [they] [know] [what] was coming."),
    ("Has the river flooded before?", "Never [in] [living] [memory] [has] it risen so high."),
    ("Did anyone object?", "Nowhere [in] [the] [minutes] [is] an objection recorded."),
    ("Do they allow food inside?", "On no account [may] [visitors] [bring] [drinks] in."),
    ("Was the decision quick?", "Only later [did] [the] [committee] [explain] its reasoning."),
    ("Did the storm ease?", "Not until [dawn] [did] [the] [wind] drop."),
  ]),

dict(
  target="Result clause with <i>so</i> or <i>such</i>",
  why="<i>So</i> goes with an adjective or adverb and <i>such</i> with a noun phrase; either is completed by a <i>that</i> clause: {ans}.",
  extras=["too"],
  items=[
    ("Was the hall crowded?", "It was [so] [full] [that] [we] stood at the back."),
    ("How was the exam?", "It was [such] [a] [long] [paper] that nobody finished."),
    ("Did you finish the novel?", "It was [so] [dense] [that] [I] gave up."),
    ("Was the talk clear?", "She spoke [so] [quickly] [that] [few] could follow."),
    ("Is the lab cold?", "It's [so] [cold] [that] [we] wear coats inside."),
    ("How was the storm?", "It was [such] [a] [shock] [that] classes were cancelled."),
    ("Did the plan work?", "It was [so] [simple] [that] [everyone] agreed immediately."),
    ("Was the queue long?", "There were [so] [many] [people] [that] we left."),
    ("How is the new building?", "It's [such] [a] [maze] [that] I get lost."),
    ("Did you like the film?", "It was [so] [slow] [that] [I] fell asleep."),
    ("Was the evidence strong?", "It was [so] [convincing] [that] [nobody] argued."),
    ("How was the first week?", "There was [so] [much] [reading] [that] I panicked."),
    ("Is the trail difficult?", "It's [such] [a] [steep] [climb] that few attempt it."),
    ("Did the machine work?", "It made [so] [much] [noise] [that] we switched it off."),
    ("Was the room quiet?", "It was [so] [silent] [that] [every] cough carried."),
    ("How was her accent?", "It was [so] [faint] [that] [I] never noticed."),
    ("Did the crowd enjoy it?", "It was [such] [a] [success] [that] they added a date."),
    ("Is the deadline tight?", "There's [so] [little] [time] [that] we may postpone."),
    ("Was the lecture dull?", "It was [so] [repetitive] [that] [half] the room left."),
    ("How did the trial go?", "The results were [so] [clear] [that] [no] follow-up was needed."),
  ]),

dict(
  target="Degree with <i>too</i> and <i>enough</i>",
  why="<i>Too</i> comes before an adjective and <i>enough</i> comes after it: {ans}.",
  extras=["so"],
  items=[
    ("Why are you returning the textbook?", "It wasn't [detailed] [enough] [for] [this] course."),
    ("Can we fit everyone in?", "The room isn't [big] [enough] [to] [hold] thirty."),
    ("Why not walk?", "It's [too] [far] [to] [walk] before nine."),
    ("Did you buy the laptop?", "It was [too] [expensive] [for] [my] budget."),
    ("Can he reach the shelf?", "He isn't [tall] [enough] [to] [reach] it."),
    ("Why did you leave early?", "It was [too] [loud] [for] [me] to concentrate."),
    ("Is the soup ready?", "It's [still] [too] [hot] [to] eat."),
    ("Did the plan work?", "We didn't have [enough] [time] [to] [test] it."),
    ("Can we finish today?", "There aren't [enough] [hours] [left] [to] finish."),
    ("Why not take the early flight?", "It leaves [too] [early] [for] [me] to manage."),
    ("Is the essay long enough?", "It isn't [quite] [long] [enough] [yet]."),
    ("Did she qualify?", "She wasn't [fast] [enough] [in] [the] final heat."),
    ("Can I read it tonight?", "It's [far] [too] [long] [for] one evening."),
    ("Why is the sample unusable?", "It wasn't [large] [enough] [to] [analyze] properly."),
    ("Should we hire another person?", "One assistant isn't [enough] [for] [a] [project] this size."),
    ("Did you take the seminar?", "It was [too] [advanced] [for] [a] first-year student."),
    ("Is the bridge safe?", "It isn't [strong] [enough] [for] [heavy] vehicles."),
    ("Why the extra chairs?", "There weren't [enough] [seats] [for] [the] guests."),
    ("Can we swim here?", "The water is [too] [cold] [to] [stay] in long."),
    ("Did the argument convince you?", "It wasn't [specific] [enough] [to] [change] my mind."),
  ]),
]
