# -*- coding: utf-8 -*-
"""HARD tier: reporting passives, modal perfect passives, nested questions, quantifier relatives, ellipsis."""

PATTERNS = [
dict(
  hard=True,
  target="Reporting passive with a perfect infinitive",
  why="<i>Is said/believed/thought to have</i> plus a past participle reports a claim about an earlier event: {ans}.",
  extras=["says", "has"],
  items=[
    ("How old is the manuscript?", "The text [is] [said] [to] [have] [been] [written] in the ninth century."),
    ("Did the company lose money?", "The firm [is] [believed] [to] [have] [lost] [millions] last year."),
    ("Was the site occupied earlier?", "The valley [is] [thought] [to] [have] [been] [settled] much earlier."),
    ("Is the painting genuine?", "It [is] [now] [known] [to] [have] [been] copied later."),
    ("Did she write the letters?", "She [is] [reported] [to] [have] [destroyed] [most] of them."),
    ("Was the treaty signed there?", "The agreement [is] [understood] [to] [have] [been] [drafted] elsewhere."),
    ("How long did it stand?", "The tower [is] [estimated] [to] [have] [stood] [for] two centuries."),
    ("Did the species survive?", "The bird [is] [presumed] [to] [have] [become] [extinct] long ago."),
    ("Was the fire accidental?", "The blaze [is] [alleged] [to] [have] [been] [started] deliberately."),
    ("Is the recipe original?", "The dish [is] [held] [to] [have] [originated] [in] the north."),
    ("Did he study there?", "He [is] [supposed] [to] [have] [trained] [under] a master."),
    ("Was the road Roman?", "The route [is] [considered] [to] [have] [followed] [an] older track."),
    ("Did the population fall?", "Numbers [are] [thought] [to] [have] [halved] [within] a decade."),
    ("Was the letter forged?", "The document [is] [suspected] [to] [have] [been] [altered] afterwards."),
    ("Did the glacier retreat?", "The ice [is] [known] [to] [have] [retreated] [steadily] for a century."),
    ("Was the theory his?", "The idea [is] [claimed] [to] [have] [originated] [with] a student."),
    ("Did trade continue?", "Exchange [is] [assumed] [to] [have] [persisted] [through] the war."),
    ("Was the temple older?", "The shrine [is] [reckoned] [to] [have] [predated] [the] city."),
    ("Did the author revise it?", "The novel [is] [said] [to] [have] [been] [rewritten] three times."),
    ("Was the population larger?", "The town [is] [believed] [to] [have] [held] [twice] that number."),
  ]),

dict(
  hard=True,
  target="Modal perfect passive",
  why="A modal followed by <i>have been</i> plus a past participle judges something that was or was not done to the subject: {ans}.",
  extras=["was", "were"],
  items=[
    ("Did anyone tell you?", "No; we [should] [have] [been] [informed] [much] [earlier]."),
    ("Was the form checked?", "It [ought] [to] [have] [been] [verified] [before] filing."),
    ("Did the alarm sound?", "It [must] [have] [been] [switched] [off] [overnight]."),
    ("Was the sample kept cold?", "It [should] [have] [been] [refrigerated] [on] [arrival]."),
    ("Did they warn the staff?", "Everyone [could] [have] [been] [warned] [by] [email]."),
    ("Was the data backed up?", "It [might] [have] [been] [copied] [to] [the] server."),
    ("Did anyone sign it?", "The form [should] [have] [been] [countersigned] [by] [two] people."),
    ("Was the room prepared?", "It [ought] [to] [have] [been] [cleaned] [that] morning."),
    ("Did they test the wiring?", "It [must] [have] [been] [inspected] [at] [installation]."),
    ("Was the patient told?", "She [should] [have] [been] [given] [the] [results] sooner."),
    ("Did the parcel get sent?", "It [may] [have] [been] [dispatched] [earlier] [this] week."),
    ("Was the error caught?", "It [could] [have] [been] [spotted] [during] [proofreading]."),
    ("Did anyone review it?", "The draft [ought] [to] [have] [been] [read] [by] someone."),
    ("Was the gate locked?", "It [should] [have] [been] [secured] [after] [closing]."),
    ("Did they record the session?", "It [might] [have] [been] [filmed] [without] [permission]."),
    ("Was the budget approved?", "It [must] [have] [been] [signed] [off] [already]."),
    ("Did the notice go up?", "It [should] [have] [been] [posted] [a] [week] earlier."),
    ("Was the equipment returned?", "It [ought] [to] [have] [been] [logged] [back] in."),
    ("Did anyone check the seal?", "It [could] [have] [been] [broken] [in] [transit]."),
    ("Was the decision minuted?", "It [should] [have] [been] [recorded] [in] [the] minutes."),
  ]),

dict(
  hard=True,
  target="Nested embedded question",
  why="A question inside a question keeps statement order at every level, however deep the nesting: {ans}.",
  extras=["did", "does"],
  items=[
    ("Why did the committee change the rule?", "Nobody seems to know [why] [the] [committee] [decided] [what] [it] did."),
    ("Where is the report?", "I can't remember [where] [she] [said] [she] [had] [filed] it."),
    ("When will they announce?", "No one is certain [when] [the] [office] [expects] [to] [publish] the list."),
    ("Who approved the change?", "It's unclear [who] [the] [department] [believes] [authorised] [the] revision."),
    ("How much did it cost?", "Nobody told us [how] [much] [the] [college] [had] [already] spent."),
    ("Which version is current?", "I'm not sure [which] [draft] [the] [editor] [thinks] [is] final."),
    ("Why was it delayed?", "We never learned [why] [the] [shipment] [took] [as] [long] as it did."),
    ("Who is presenting?", "Ask him [who] [the] [organisers] [have] [asked] [to] speak."),
    ("When did she leave?", "Nobody recalls [when] [it] [was] [that] [she] [resigned]."),
    ("Where did the funding go?", "Auditors are asking [where] [the] [money] [the] [grant] [provided] went."),
    ("How does it work?", "Explain [how] [the] [system] [decides] [which] [files] to keep."),
    ("Why did they refuse?", "Nobody understands [why] [the] [board] [rejected] [what] [everyone] wanted."),
    ("Which candidate won?", "I forget [which] [applicant] [the] [panel] [said] [it] preferred."),
    ("When is the deadline?", "Check [when] [the] [registrar] [says] [the] [forms] are due."),
    ("Who wrote the guidance?", "It's uncertain [who] [in] [the] [ministry] [drafted] [the] wording."),
    ("How long will it take?", "No one can say [how] [long] [the] [repairs] [are] [likely] to take."),
    ("Why is the figure wrong?", "We asked [why] [the] [total] [differed] [from] [what] we reported."),
    ("Where should I send it?", "Find out [where] [the] [office] [wants] [the] [copies] sent."),
    ("Which chapter is assessed?", "Nobody said [which] [section] [the] [examiner] [intends] [to] test."),
    ("When did the policy change?", "Records show [when] [the] [rule] [was] [amended] [and] why."),
  ]),

dict(
  hard=True,
  target="Quantifier with <i>of whom</i> or <i>of which</i>",
  why="A non-restrictive clause can open with a quantifier plus <i>of whom</i> or <i>of which</i>, which replaces a pronoun rather than adding one: {ans}.",
  extras=["them", "they"],
  items=[
    ("How many applied?", "Forty people applied, [many] [of] [whom] [had] [no] [experience]."),
    ("Were the samples usable?", "We took twelve samples, [most] [of] [which] [were] [later] [discarded]."),
    ("Did the students attend?", "Thirty enrolled, [several] [of] [whom] [dropped] [out] [early]."),
    ("How were the reviews?", "There were four reviews, [none] [of] [which] [recommended] [outright] [rejection]."),
    ("Who came to the talk?", "Sixty attended, [half] [of] [whom] [were] [visiting] [staff]."),
    ("Were the sources reliable?", "He cites nine sources, [two] [of] [which] [no] [longer] [exist]."),
    ("Did the trials succeed?", "They ran six trials, [all] [of] [which] [produced] [similar] [results]."),
    ("How many buildings survive?", "Eleven remain, [some] [of] [which] [are] [badly] [damaged]."),
    ("Who signed the letter?", "Twenty scholars signed, [one] [of] [whom] [later] [withdrew] [support]."),
    ("Were the answers useful?", "We received many replies, [few] [of] [which] [answered] [the] [question]."),
    ("How many species were found?", "They recorded eight, [three] [of] [which] [were] [entirely] [new]."),
    ("Did the committee agree?", "Nine members voted, [most] [of] [whom] [supported] [the] [motion]."),
    ("Were the letters preserved?", "Hundreds were written, [only] [a] [handful] [of] [which] [survive]."),
    ("Who funded the work?", "Three bodies funded it, [each] [of] [which] [set] [separate] [conditions]."),
    ("Did the machines fail?", "Four units shipped, [two] [of] [which] [failed] [within] [days]."),
    ("How many attended the workshop?", "Twenty came, [the] [majority] [of] [whom] [were] [postgraduates]."),
    ("Were the maps accurate?", "He drew several maps, [none] [of] [which] [matched] [the] [survey]."),
    ("Who contributed chapters?", "Ten authors contributed, [five] [of] [whom] [had] [never] [published]."),
    ("Did the samples degrade?", "We stored sixteen, [many] [of] [which] [degraded] [over] [winter]."),
    ("Were the questions answered?", "She took twelve questions, [most] [of] [which] [she] [answered] [fully]."),
  ]),

dict(
  hard=True,
  target="Ellipsis with <i>so</i>, <i>neither</i> and <i>nor</i>",
  why="A short agreeing clause inverts the auxiliary after <i>so</i>, <i>neither</i> or <i>nor</i>, and the main verb is left out: {ans}.",
  extras=["too", "also"],
  items=[
    ("I thought the lecture was excellent.", "So [did] [I], [and] [so] [did] the others."),
    ("I hadn't heard about the change.", "Neither [had] [we], [nor] [had] [the] [department]."),
    ("I can't make the meeting.", "Neither [can] [I], [and] [nor] [can] [my] partner."),
    ("She finished early.", "So [did] [her] [partner], [and] [so] did mine."),
    ("I don't agree with the method.", "Nor [do] [I], [and] [neither] [does] [my] supervisor."),
    ("They were surprised by the result.", "So [was] [I], [and] [so] [were] [the] reviewers."),
    ("I've never used that software.", "Neither [have] [I], [nor] [has] [anyone] [here]."),
    ("He should have asked first.", "So [should] [she], [and] [so] [should] [the] rest."),
    ("I won't be at the seminar.", "Neither [will] [I], [and] [nor] [will] [my] group."),
    ("The first draft was weak.", "So [was] [the] [second], [and] [so] [was] the third."),
    ("I didn't notice the error.", "Nor [did] [anyone] [else], [and] [neither] [did] I."),
    ("She has already submitted.", "So [have] [I], [and] [so] [has] [the] group."),
    ("I couldn't follow the argument.", "Neither [could] [we], [nor] [could] [the] [chair]."),
    ("They arrived on time.", "So [did] [the] [speakers], [and] [so] did we."),
    ("I'd rather not present first.", "Neither [would] [I], [and] [nor] [would] [she]."),
    ("The data looked odd to me.", "So [they] [did] [to] [us], [and] [to] the reviewers."),
    ("He isn't coming tomorrow.", "Neither [is] [she], [nor] [are] [the] [others]."),
    ("I liked the second chapter best.", "So [did] [I], [and] [so] [did] [my] tutor."),
    ("We hadn't been told either.", "Nor [had] [they], [and] [neither] [had] [the] office."),
    ("I'm not convinced by the figures.", "Neither [am] [I], [and] [nor] [is] [the] editor."),
  ]),
]
