# -*- coding: utf-8 -*-
"""Conditionals, passive voice, relative clauses."""

PATTERNS = [
dict(
  target="Present unreal conditional",
  why="An unreal conditional uses a past form in the <i>if</i> clause and <i>would</i> or <i>could</i> plus a base verb in the other: {ans}.",
  extras=["was"],
  items=[
    ("Should I take the 8 a.m. section?", "If I [were] [you], I [would] [definitely] [choose] the afternoon one."),
    ("Do you think I should email her?", "If I [were] [in] [your] [position], I [would] wait a day."),
    ("Would you switch majors?", "If the program [were] [less] [rigid], I [would] consider it."),
    ("Can I afford another course?", "If tuition [weren't] [so] [high], you [could] take two."),
    ("Why not join the trip?", "If I [had] [more] [free] [time], I [would] come along."),
    ("Should we present first?", "If we [went] [last], the audience [would] [already] be tired."),
    ("Is she going to apply?", "If she [felt] [more] [confident], she [would] apply today."),
    ("Do you want the window seat?", "If it [were] [colder], I [would] [prefer] the aisle."),
    ("Should I buy the textbook?", "If I [needed] [it] [daily], I [would] buy a copy."),
    ("Would you move off campus?", "If rent [were] [cheaper], I [would] [leave] tomorrow."),
    ("Can we finish tonight?", "If we [started] [now], we [might] [manage] it."),
    ("Is the lab too far?", "If there [were] [a] [shuttle], nobody [would] complain."),
    ("Should I speak to the dean?", "If I [were] [worried], I [would] [go] straight there."),
    ("Would you take the night shift?", "If the pay [were] [any] [better], I [would] consider it."),
    ("Do you think she would help?", "If you [asked] [politely], she [would] [probably] agree."),
    ("Is the course worth it?", "If I [were] [starting] [over], I [would] take it again."),
    ("Should we invite the whole group?", "If the room [were] [bigger], we [could] [invite] everyone."),
    ("Would you learn another language?", "If I [had] [a] [free] [term], I would study Japanese."),
    ("Can I borrow your notes?", "If they [were] [legible], I [would] [share] them gladly."),
    ("Should I retake the test?", "If I [were] [in] [your] [place], I would retake it."),
  ]),

dict(
  target="Past unreal conditional",
  why="A past unreal conditional pairs <i>had</i> plus a past participle with <i>would have</i> plus a past participle: {ans}.",
  extras=["has"],
  items=[
    ("Why did the bridge fail?", "The damage [would] [have] [been] [detected] earlier if anyone had checked."),
    ("Did you know about the change?", "I [would] [have] [come] [earlier] if someone had told me."),
    ("Why didn't she apply?", "She [would] [have] [applied] [if] the deadline had been later."),
    ("Was the trip a mistake?", "If we [had] [checked] [the] [forecast], we would have stayed home."),
    ("Did you miss the bus?", "I [would] [have] [caught] [it] if I had left sooner."),
    ("Why was the data lost?", "Nothing [would] [have] [disappeared] [if] the backup had run."),
    ("Did he fail the course?", "He [would] [have] [passed] [with] a little more revision."),
    ("Was the meeting useful?", "If they [had] [sent] [an] [agenda], it would have been shorter."),
    ("Why did the experiment fail?", "It [would] [have] [worked] [if] the sample had been fresh."),
    ("Did you enjoy the concert?", "I [would] [have] [stayed] [longer] if the seats had been better."),
    ("Why weren't you told?", "Someone [would] [have] [mentioned] [it] if they had known."),
    ("Was the flight delayed?", "If the weather [had] [held], we [would] [have] landed on time."),
    ("Did she take the job?", "She [would] [have] [accepted] [if] the salary had been higher."),
    ("Why was the room double-booked?", "The clash [would] [have] [been] [avoided] with one shared calendar."),
    ("Did you finish the draft?", "I [would] [have] [finished] [it] if the library had stayed open."),
    ("Was the class cancelled?", "They [would] [have] [emailed] [everyone] if it had been cancelled."),
    ("Why did the team lose?", "We [would] [have] [won] [if] our captain had played."),
    ("Did anyone notice the error?", "It [would] [have] [been] [caught] during a second reading."),
    ("Why is the report late?", "If I [had] [started] [the] [work] in September, it would already be done."),
    ("Did he get the message?", "He [would] [have] [replied] [if] his phone had worked."),
  ]),

dict(
  target="Future real conditional",
  why="A likely future condition takes a present form after <i>if</i> and <i>will</i> in the main clause: {ans}.",
  extras=["would"],
  items=[
    ("Are you going to the game?", "If the rain [stops], I [will] [walk] [over] with you."),
    ("Will you finish tonight?", "If I [keep] [this] [pace], I [will] be done by ten."),
    ("Should I wait for you?", "If the meeting [runs] [long], I [will] [text] you."),
    ("Are you taking the exam early?", "If they [allow] [it], I [will] [happily] sit it on Monday."),
    ("Will the shop still be open?", "If we [leave] [now], we [will] [get] there in time."),
    ("Is the trip still on?", "If enough people [sign] [up], the office [will] [surely] confirm it."),
    ("Will you need a ride?", "If my bike [is] [still] [broken], I [will] ask you."),
    ("Are you applying this year?", "If my scores [improve] [enough], I [will] [certainly] apply again."),
    ("Will she join the lab?", "If the funding [comes] [through], she [will] [start] in June."),
    ("Should we book the room?", "If we [wait] [any] [longer], someone [will] take it."),
    ("Will the package arrive today?", "If it [ships] [this] [morning], it [will] arrive by six."),
    ("Are you coming to the review?", "If I [finish] [the] [problem] [set], I will come."),
    ("Will the price go up?", "If demand [stays] [high], the fee [will] [rise] again."),
    ("Should I bring my laptop?", "If the wifi [works], we [will] [certainly] [need] it."),
    ("Will they extend the deadline?", "If enough students [ask] [again], they [will] [probably] extend it."),
    ("Are you going to the conference?", "If my abstract [is] [accepted], I [will] [gladly] fly out."),
    ("Will the bus be crowded?", "If we [board] [at] [the] [first] stop, we will sit together."),
    ("Should we split the cost?", "If everyone [contributes] [something], the total [will] [be] manageable."),
    ("Will you keep the apartment?", "If the rent [stays] [flat], I [will] [probably] renew."),
    ("Are you free on Friday?", "If nothing [changes] [suddenly], I [will] [be] around all day."),
  ]),

dict(
  target="Passive voice",
  why="The passive is a form of <i>be</i> plus a past participle: {ans}. <i>Been</i> appears only after <i>have</i> or <i>had</i>.",
  extras=["been"],
  items=[
    ("Did someone already grade the midterms?", "Yes, they [were] [all] [posted] [online] this morning."),
    ("Who cleaned the lab?", "It [was] [cleaned] [by] [the] night staff."),
    ("Did they cancel the seminar?", "The seminar [was] [moved] [to] [another] building."),
    ("Is the bridge open?", "It [is] [being] [repaired] [this] month."),
    ("Who wrote this report?", "It [was] [written] [by] [three] different people."),
    ("Did the museum buy the painting?", "The painting [was] [donated] [by] [a] former student."),
    ("Are the results ready?", "They [are] [still] [being] [checked] by the committee."),
    ("Did they fix the heater?", "It [was] [replaced] [over] [the] weekend."),
    ("Who chose the topic?", "It [was] [decided] [at] [the] first meeting."),
    ("Is the article published?", "It [was] [accepted] [but] [not] printed yet."),
    ("Did anyone survey the site?", "The site [was] [surveyed] [before] [the] road was built."),
    ("Are the books catalogued?", "Most [were] [catalogued] [in] [the] 1990s."),
    ("Who funds the program?", "It [is] [funded] [by] [a] private foundation."),
    ("Did they announce the winners?", "The names [were] [read] [out] [at] the ceremony."),
    ("Is the data stored safely?", "Everything [is] [backed] [up] [every] night."),
    ("Did someone move my desk?", "It [was] [shifted] [during] [the] renovation."),
    ("Who translated the manuscript?", "It [was] [translated] [by] [two] scholars."),
    ("Are the samples ready?", "They [were] [frozen] [as] [soon] as they arrived."),
    ("Did they repaint the hall?", "It [was] [painted] [over] [the] summer."),
    ("Is the film finished?", "It [is] [being] [edited] [right] now."),
  ]),

dict(
  target="Passive with a modal",
  why="After a modal the passive keeps <i>be</i> plus a past participle: {ans}.",
  extras=["been"],
  items=[
    ("What should we do with the extra copies?", "They [should] [be] [returned] [to] the front desk."),
    ("Can the deadline move?", "It [can] [be] [extended] [only] by the department."),
    ("What about the broken chair?", "It [must] [be] [replaced] [before] the inspection."),
    ("Where do the forms go?", "They [have] [to] [be] [signed] by an advisor."),
    ("Can we reuse the slides?", "They [may] [be] [shared] [with] written permission."),
    ("What happens to the samples?", "They [will] [be] [stored] [at] low temperature."),
    ("Is the essay handwritten?", "It [should] [be] [typed] [and] double spaced."),
    ("Who approves the budget?", "It [must] [be] [approved] [by] the committee."),
    ("Can I keep the equipment?", "It [has] [to] [be] [logged] back in."),
    ("What about the old files?", "They [can] [be] [archived] [after] two years."),
    ("Should we email the draft?", "It [ought] [to] [be] [reviewed] first."),
    ("Is the door always locked?", "It [should] [be] [locked] [after] six."),
    ("What about the leftover materials?", "They [could] [be] [donated] [to] the workshop."),
    ("Can the test be retaken?", "It [may] [be] [repeated] [once] per term."),
    ("Who cleans the glassware?", "It [must] [be] [rinsed] [immediately] after use."),
    ("What about late submissions?", "They [will] [be] [marked] [down] automatically."),
    ("Can we film the lecture?", "It [cannot] [be] [recorded] [without] consent."),
    ("Where should the poster go?", "It [should] [be] [mounted] [near] the entrance."),
    ("Is the software updated?", "It [needs] [to] [be] [patched] this week."),
    ("What about the survey data?", "It [must] [be] [anonymized] [before] analysis."),
  ]),

dict(
  target="Relative clause with <i>who</i>",
  why="<i>Who</i> introduces a clause describing a person and acts as its subject, so no second subject pronoun follows: {ans}.",
  extras=["which"],
  items=[
    ("Which professor do you mean?", "I mean the professor [who] [teaches] [the] [morning] seminar."),
    ("Who is presenting first?", "The student [who] [signed] [up] [earliest] goes first."),
    ("Who should I ask about housing?", "Talk to the person [who] [handles] [off-campus] [listings]."),
    ("Who found the error?", "It was a reviewer [who] [checked] [the] [appendix] carefully."),
    ("Which classmate helped you?", "It was the one [who] [sits] [near] [the] window."),
    ("Who runs the writing center?", "A graduate student [who] [specializes] [in] [rhetoric] runs it."),
    ("Who called about the room?", "Someone [who] [works] [in] [facilities] left a message."),
    ("Which of the tutors is best?", "The tutor [who] [explains] [things] [slowly] helped me most."),
    ("Who organized the trip?", "Two students [who] [went] [last] [year] planned it."),
    ("Who is the keynote speaker?", "A researcher [who] [studies] [coastal] [erosion] is speaking."),
    ("Who lent you the book?", "It was a friend [who] [took] [the] [course] before me."),
    ("Who complained about the noise?", "It was a neighbor [who] [lives] [one] [floor] above."),
    ("Which applicant did they choose?", "They chose the one [who] [had] [field] [experience] already."),
    ("Who fixed the projector?", "A technician [who] [comes] [every] [week] repaired it."),
    ("Who wrote the recommendation?", "It was a supervisor [who] [knows] [my] [work] well."),
    ("Which student won?", "The student [who] [submitted] [the] [earliest] draft won."),
    ("Who should lead the group?", "Anyone [who] [has] [presented] [before] would do."),
    ("Who reported the leak?", "A cleaner [who] [noticed] [it] [at] dawn reported it."),
    ("Who is covering the class?", "A lecturer [who] [taught] [it] [two] years ago is covering."),
    ("Who recommended this place?", "A coworker [who] [lives] [nearby] [suggested] it."),
  ]),

dict(
  target="Possessive relative pronoun <i>whose</i>",
  why="<i>Whose</i> shows possession and attaches directly to the noun it owns: {ans}. <i>Who</i> cannot be followed by a noun this way.",
  extras=["who"],
  items=[
    ("Which professor are you talking about?", "I mean the one [whose] [seminar] [we] [all] [attended] last week."),
    ("Who is the student you mentioned?", "It's the one [whose] [poster] [won] [the] prize."),
    ("Which neighbor complained?", "The family [whose] [dog] [barks] [all] night complained."),
    ("Who should I contact?", "Contact the colleague [whose] [name] [is] [on] the form."),
    ("Which building is closed?", "It's the one [whose] [roof] [was] [damaged] in the storm."),
    ("Who lost a notebook?", "The student [whose] [initials] [are] [inside] the cover."),
    ("Which author do you mean?", "I mean the one [whose] [first] [novel] [we] read."),
    ("Who is presenting next?", "The pair [whose] [experiment] [failed] [twice] is presenting."),
    ("Which car got towed?", "It was the one [whose] [permit] [had] [expired] last month."),
    ("Who runs the fund?", "A trustee [whose] [family] [founded] [the] college runs it."),
    ("Which team forfeited?", "The team [whose] [goalkeeper] [was] [injured] forfeited."),
    ("Who is the guest lecturer?", "A scientist [whose] [research] [changed] [the] field is speaking."),
    ("Which apartment flooded?", "It was the unit [whose] [pipes] [burst] [in] January."),
    ("Who gave you the reference?", "A mentor [whose] [lab] [I] [joined] last summer did."),
    ("Which article should I read?", "Read the one [whose] [conclusion] [everyone] [disputes]."),
    ("Who owns the bike outside?", "A resident [whose] [apartment] [faces] [the] courtyard owns it."),
    ("Which company won the contract?", "It was the firm [whose] [bid] [came] [in] lowest."),
    ("Who is your favorite composer?", "Someone [whose] [work] [almost] [nobody] performs now."),
    ("Which candidate impressed you?", "The one [whose] [answers] [were] [the] shortest impressed me."),
    ("Who left the umbrella?", "A visitor [whose] [badge] [is] [still] at reception left it."),
  ]),

dict(
  target="Reduced relative clause",
  why="A relative clause can drop its pronoun and verb, leaving a participle that modifies the noun directly: {ans}.",
  extras=["which"],
  items=[
    ("Which edition should I cite?", "Use the version [published] [by] [the] [university] press."),
    ("Which sample failed?", "The one [stored] [at] [room] [temperature] failed."),
    ("Which students got the email?", "Everyone [registered] [for] [the] [seminar] got it."),
    ("Which file is current?", "The one [saved] [on] [the] [shared] drive is current."),
    ("Which road is closed?", "The route [running] [past] [the] [stadium] is closed."),
    ("Which candidates advanced?", "Those [selected] [by] [the] [first] panel advanced."),
    ("Which books are on reserve?", "The titles [listed] [on] [the] [syllabus] are on reserve."),
    ("Which data did you use?", "I used the set [collected] [during] [the] [winter] survey."),
    ("Which lamp is broken?", "The one [hanging] [above] [the] [side] table is broken."),
    ("Which paper won?", "The study [comparing] [two] [teaching] [methods] won."),
    ("Which group is late?", "The team [travelling] [from] [the] [north] campus is late."),
    ("Which chapter matters most?", "The section [dealing] [with] [sampling] [error] matters most."),
    ("Which photos are usable?", "Only the shots [taken] [before] [the] [rain] are usable."),
    ("Which students need help?", "Anyone [struggling] [with] [the] [second] problem set does."),
    ("Which building has the lab?", "The one [named] [after] [the] [founder] has it."),
    ("Which version is final?", "The draft [approved] [at] [the] [last] meeting is final."),
    ("Which route do you take?", "I take the path [cutting] [through] [the] [old] quad."),
    ("Which applicants were interviewed?", "Those [nominated] [by] [their] [departments] were interviewed."),
    ("Which machine is down?", "The printer [located] [near] [the] [stairs] is down."),
    ("Which results surprised you?", "The figures [reported] [in] [the] [appendix] surprised me."),
  ]),
]
